### ISSUE TITLE
有关 `export` 无法导出 `命令方块` 的问题

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#100]
**摘要**
在利用 `export` 导出含有命令方块的结构时会导出失败
***
**复现步骤**
1. 让机器人进入一个自然生成的超平坦地图的租赁服，且地图未做过任何更改、地图在先前没有加入过任何玩家
2. 授予机器人管理员权限，若机器人没有管理员权限的话
3. 在位置 `(1000,100,1000)` 处放置 `chain_command_block`
4. 将机器人传送至 `(1000,100,1000)` 处并在控制台执行

     > set 1000 100 1000
     > setend 1000 100 1000
6. 在控制台执行 `export -p testcb.bdx`
7. 在控制台执行 `exit`
8. 拆除于步骤 `3` 放置的命令方块并让机器人重新进入游戏
9. 执行步骤 `4` 和步骤 `5`
***
**观察结果**
在执行完步骤 `5` 后，控制台返回下述内容
```
Hit Memory  [976 976]
Hit Memory  [976 992]
Hit Memory  [992 992]
Hit Memory  [992 976]
Master Node [992 992] all fetched
Hop Left:  0
Begin Fast Hopping
Fast Hopping Done
Hop Left:  0
 SUCCESS  all chunks successfully fetched!
EXPORT >> Exporting...
go routine @ fastbuilder.task export crashed  interface conversion: interface {} is nil, not string
```
在执行完步骤 `8` 后，控制台返回下述内容
```
Hit Memory  [992 976]
Hit Memory  [992 992]
Hit Memory  [976 976]
Hit Memory  [976 992]
Master Node [992 992] all fetched
Hop Left:  0
Begin Fast Hopping
Fast Hopping Done
Hop Left:  0
 SUCCESS  all chunks successfully fetched!
EXPORT >> Exporting...
EXPORT >> Writing output file
EXPORT >> File signed successfully
EXPORT >> Successfully exported your structure to testcb.bdx
```
***
**预期结果**
无论是执行完步骤 `5` 还是步骤 `8` ，控制台应当都返回下述内容
```
Hit Memory  [992 976]
Hit Memory  [992 992]
Hit Memory  [976 976]
Hit Memory  [976 992]
Master Node [992 992] all fetched
Hop Left:  0
Begin Fast Hopping
Fast Hopping Done
Hop Left:  0
 SUCCESS  all chunks successfully fetched!
EXPORT >> Exporting...
EXPORT >> Writing output file
EXPORT >> File signed successfully
EXPORT >> Successfully exported your structure to testcb.bdx
```
***
**备注**
- 曾经与 `export` 相关的 `命令方块` 议题是 #94 
     > 因此，若本议题被确定会被解决，建议在解决本议题后重新打开 #94 并进行相应的修复
- 除此之外，曾经修复过 #78 ，且 `Bug` 的观察结果基本与本议题相同。

**Comment by LNSSPsd** [comment]
May have the same cause as #99.

**Comment by LNSSPsd** [comment]
Could you provide the error shown in the latest version? As I think that one would show stack trace.

**Comment by Happy2018new** [comment]
附加资料
@LNSSPsd 
***
Hit Memory  [30000 30000]
Hit Memory  [29984 30000]
Hit Memory  [30000 29984]
Hit Memory  [29984 29984]
Master Node [30000 30000] all fetched
Hop Left:  0
Begin Fast Hopping
Fast Hopping Done
Hop Left:  0
 SUCCESS  all chunks successfully fetched!
EXPORT >> Exporting...
goroutine 19520 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
phoenixbuilder/io/special_tasks.CreateExportTask.func5.1()
        phoenixbuilder/io/special_tasks/export.go:150 +0x39
panic({0x7ff6661067c0, 0xc0006828d0})
        runtime/panic.go:838 +0x207
phoenixbuilder/io/special_tasks.CreateExportTask.func5()
        phoenixbuilder/io/special_tasks/export.go:200 +0xd94
created by phoenixbuilder/io/special_tasks.CreateExportTask
        phoenixbuilder/io/special_tasks/export.go:146 +0x9cf
go routine @ fastbuilder.task export crashed  interface conversion: interface {} is nil, not string

**Comment by LNSSPsd** [comment]
Working on it.

**Comment by Happy2018new** [comment]
所以 #99 是没有修复吗？

**Comment by LNSSPsd** [comment]
> 所以 #99 是没有修复吗？ @LNSSPsd

y, 可以修复后提交 pull request, 不建议 reopen
