### ISSUE TITLE
关于OmegaSide并发写入的错误

### ISSUE THREAD

**Issue by Liliya233** [LNSSPsd/PhoenixBuilder#102]
已在 #97 中详细描述该错误

经过测试，在`PhoenixBuilder 3.3.1 (f28660f)`中仍可复现该错误

**Comment by Happy2018new** [comment]
实际上，`PhoenixBuilder` 中内置的 `Omega System` 早已经不是最新版本了，甚至连 `lua` 都还未采用。
所以，可能是这个的问题，你可能需要使用启动器？

**Comment by Liliya233** [comment]
> 实际上，`PhoenixBuilder` 中内置的 `Omega System` 早已经不是最新版本了，甚至连 `lua` 都还未采用。 所以，可能是这个的问题，你可能需要使用启动器？

是的，我也注意到这个情况

**Comment by LNSSPsd** [comment]
> 实际上，`PhoenixBuilder` 中内置的 `Omega System` 早已经不是最新版本了，甚至连 `lua` 都还未采用。
> 所以，可能是这个的问题，你可能需要使用启动器？

Merging process of the external omega project is welcomed but not required.

However, this issue is about a bug, and will be fixed.
