### ISSUE TITLE
编译后运行 FB 报错

### ISSUE THREAD

**Issue by Inotart** [LNSSPsd/PhoenixBuilder#105]
![image](https://user-images.githubusercontent.com/101685021/197207839-917d5ab9-a11a-45f8-918a-62db2f7d46c6.png)
改的部分只涉及到了print部分
上面的调试的部分是为了看报错的地方
![image](https://user-images.githubusercontent.com/101685021/197208007-415a9cc2-4ac6-4a66-b60a-76d0171abfb2.png)

**Comment by Happy2018new** [comment]
This is not a bug, so please close this issue as not plan.
Thanks.

**Comment by Inotart** [comment]
你好,我目前不在，如果你只是看到论坛邮件就不用回复了
