### ISSUE TITLE
升级 `BDX` 中的放置方块方法

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#107]
根据 [Minecraft Wiki - Block States](https://minecraft.fandom.com/zh/wiki/%E6%96%B9%E5%9D%97%E7%8A%B6%E6%80%81) 中开头章节的描述，方块数据值（又称附加值/元数据）已正被弃用，新版本加入的方块将不再支持其。
相应截图如下。<br>
<img width="571" alt="image" src="https://user-images.githubusercontent.com/109064184/197318662-ee68a49c-6649-4c5f-863d-59e905fc436e.png">
***
正如一句俗话，上帝关上了一扇窗，那么必定会为你打开一扇窗，因此不难发现，`setblock` 命令支持传入 `Block States` 数据，相应语法如下。
```
setblock <position: x y z> <tileName: Block> [blockStates: block states] [destroy|keep|replace]
```
有关 `[blockStates: block states]` 部分，具体可见此截图<br>
<img width="388" alt="image" src="https://user-images.githubusercontent.com/109064184/197319090-2b0b4f3f-63e7-4eba-9f81-1ac3b899da51.png">
***
因此，建议将 `BDX` 中基于方块数据值（又称附加值/元数据）的放置方法升级为基于 `Block States` 的放置方法。
基于这一个升级，有下列建议。
- 基于原本的 `Operation 01 - addToBlockPalette` ，额外添加一个 `Operation - addToBlockPaletteNew` ，但方法是 `addToBlockPaletteNew; char *blockName; char *blockStates` 。其中，新添加的 `char *blockStates` 指代 `Block States:str` 在经过 `encode` 后的二进制形式。
- 基于原本的 `Operation 07 - placeBlock` ，额外添加一个 `Operation - placeBlockNew` ，但方法是 `placeBlockNew; unsigned short blockID` 。新 `Operation` 与原本的相比，就是删除了 `unsigned short blockData` 参数，因为已经在 `addToBlockPaletteNew` 中指定了 `Block States` 。

**Comment by CMA2401PT** [comment]
setblock <position: x y z> <tileName: Block> [blockStates: block states] [destroy|keep|replace]
能测试一下网易是否支持这个吗？

**Comment by Happy2018new** [comment]
```
!setblock ~ ~ ~ stained_glass ["color": "orange"]
&{CommandOrigin:{Origin:5 UUID:99a8da14-5281-11ed-b35e-28c63faeaff2 RequestID:96045347-a6a3-4114-94c0-1bc4cc561694 PlayerUniqueID:0} OutputType:4 SuccessCount:1 OutputMessages:[{Success:true Message:commands.setblock.success Parameters:[]}] DataSet:{
   "position" : {
      "x" : 6694,
      "y" : 76,
      "z" : 6675
   },
   "statusCode" : 0
}
}
```
***
@CMA2401PT

**Comment by CMA2401PT** [comment]
good job, schem 和存档导入应该能先用上

**Comment by Happy2018new** [comment]
特别地，对于含水等方块，希望可以通过一个类似于 `{"foreground": blockName:str, "background": blockName:str}` 的伪NBT（MC中实际不存在的NBT）来记录这个方块的前景层和背景层。

**Comment by Happy2018new** [comment]
> 特别地，对于含水等方块，希望可以通过一个类似于 `{"foreground": blockName:str, "background": blockName:str}` 的伪NBT（MC中实际不存在的NBT）来记录这个方块的前景层和背景层。

类似于——
```
addToBlockPaletteNew;
minecraft:wall_sign;
{
    "blockStates": ["facing_direction": 3],
    "foreground": "minecraft:sign",
    "background": "minecraft:water",
}
```

**Comment by Happy2018new** [comment]
然后顺带就把含水方块支持了吧，通过类似于 #83 中提到的方法来实现

**Comment by CMA2401PT** [comment]
不必，其实mc已经有标准的记录方式，没必要自己再创造一种新的格式了

**Comment by Happy2018new** [comment]
> 不必，其实mc已经有标准的记录方式，没必要自己再创造一种新的格式了

那怎么记录比较好呢（

**Comment by CMA2401PT** [comment]
mc怎么记录的，我们就怎么记录呗，最多加一个字符表示和以往记录的不同之处

**Comment by Happy2018new** [comment]
> 

这样如何
`placeBlockNew; unsigned short blockID(前景层); unsigned short blockID(背景层)`

**Comment by CMA2401PT** [comment]
没必要，mc有现成的方法表示是否充水

**Comment by Happy2018new** [comment]
> 没必要，mc有现成的方法表示是否充水

喵喵喵？它是如何表示的？

**Comment by CMA2401PT** [comment]
字段 water_filled=true

**Comment by LNSSPsd** [comment]
`40` - `PlaceBlockWithBlockStates`

**Comment by Happy2018new** [comment]
它的具体语法是？
@LNSSPsd

**Comment by Happy2018new** [comment]
是这样吗？
```
operation 13; BlockConstantStringID uint16; BlockStatesJSONString string
```
***
example
```
operation 13; 23; {"color":"orange"}; \x00
```

**Comment by LNSSPsd** [comment]
> 是这样吗？
> 
> ```
> operation 13; BlockConstantStringID uint16; BlockStatesJSONString string
> ```
> 
> 如果是这样，这个例子是否正确？
> 
> ```
> operation 13; 23; {"color":"orange"}; \x00
> ```
> 
> ```
> \x0d\x00\x17{"color":"orange"}\x00
> ```

正确
