### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#109]
根据 #83 的更新，希望在利用 `PhoenixBuilder` 导出文件的时候，向文件内写入 `NBT` 数据（如果存在的话）。
同时，认为每一个 `operation 39` 中记录的 `方块实体数据` 都指代的是画笔所在方块的相应数据。

**Comment by CMA2401PT** [comment]
老是在这个协议上缝缝补补好像也没啥意思，不如更充分的重构一次吧

**Comment by LNSSPsd** [comment]
### Important Note
Netease servers no longer provide full NBT data with valid tags, but in format like that: `"\x01\x00\x00\x00\x00\x01\x00\x00\x00\bsay test\"\x00\x00\x00\x00\x01\xfa\xcd\x03\x00\x00"`.
What some works depend on operation 39 that have been done before will surely not compatible with this stuff.
@Happy2018new

**Comment by Happy2018new** [comment]
我想我已经忘记了 `NBT` 的相关格式了，能否把 `"\x01\x00\x00\x00\x00\x01\x00\x00\x00\bsay test\"\x00\x00\x00\x00\x01\xfa\xcd\x03\x00\x00"` 写为 `伪 JSON` 形式？
@LNSSPsd

**Comment by LNSSPsd** [comment]
不能，它没有tag只有值

**Comment by Happy2018new** [comment]
看起来网易限制了某些方面（
如果要解决这种问题，或许可能需要一张表来对照？看起来很麻烦

**Comment by LNSSPsd** [comment]
可以自行解析 参考 [io/special_tasks/export.go](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/io/special_tasks/export.go) 的命令方块解析

**Comment by Happy2018new** [comment]
emm
能否通过请求已经保存的 `structure` 来获取完整的 `NBT` 信息？
