### ISSUE TITLE
FB 3.4.1版本 .schematic 无法正常导入

### ISSUE THREAD

**Issue by Inotart** [LNSSPsd/PhoenixBuilder#117]
1. .schematic 文件无法被正确分析 
2. .schematic 文件错误分析导入的部分是完全相同的错误区块
3. 使用 3.4.1版本的 omg 导入 .schematic 文件 同样也会出现上述第一条的错误
4. 使用 omg 导入  .schematic 文件 不会出现第2条错误,但是依然存储导入不能导全的问题

# Omg 导入模式的错误图
![7bf7cb8c6396ce0b1a5629360db9642](https://user-images.githubusercontent.com/101685021/200368247-a4973df7-cd1e-450f-8340-78180fc87671.jpg)

**Comment by Inotart** [comment]
![bd3c33521bc2bcdcf228e90f5b2a5e1](https://user-images.githubusercontent.com/101685021/200377469-1c8f164c-628a-42e4-bd0d-bd4ea7698b3a.jpg)
![6a13b0f3f7523181803556486b03221](https://user-images.githubusercontent.com/101685021/200377485-fbf36d75-cc72-4e4e-97a5-98ff6eabd0a7.jpg)
![90ec34aed4975e7be4b65be7ea3e7ed](https://user-images.githubusercontent.com/101685021/200377505-5ae0c774-4d61-42e0-9ab1-41014b0909af.jpg)

**Comment by Happy2018new** [comment]
#104 叙述了相同的问题，且应当还未被修复。

**Comment by Happy2018new** [comment]
关掉干啥，这 `Bug` 不是还没修复吗？？
