### ISSUE TITLE
3.5.0版本安卓导入schematic文件依旧故障

### ISSUE THREAD

**Issue by v2937368221** [LNSSPsd/PhoenixBuilder#120]
![Screenshot_20221115_104018](https://user-images.githubusercontent.com/118236983/201815332-05b620aa-9a51-4c20-a0fd-55f21c1b3315.jpg)
![Screenshot_20221105_213310_9143f33b2387a160d15fb9194169309e](https://user-images.githubusercontent.com/118236983/201816416-06cd91c4-91f5-4b50-8aa3-c21ceec12d5f.jpg)

**Comment by Happy2018new** [comment]
你似乎在报告已经被报告过的问题

**Comment by Happy2018new** [comment]
> 你似乎在报告已经被报告过的问题

此议题与 #117 重复。

**Comment by LNSSPsd** [comment]
Fixed at 65dbca4
