### ISSUE TITLE
read tcp wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by 666QFF** [LNSSPsd/PhoenixBuilder#125]
read tcp 192.168.1.105:63013->104.21.28.45:2053: wsarecv: An existing connection was forcibly closed by the remote host.
一直链接不是 有线网 无线网 个人热点 都连接不到   官网正常访问

![18e6af8eb42bbf8263d28ac1f1191624](https://user-images.githubusercontent.com/99183410/202613805-217fa1c8-d7d3-4c0d-9631-0d589af6b571.png)

![18e6af8eb42bbf8263d28ac1f1191624](https://user-images.githubusercontent.com/99183410/202613832-a0b91a71-bc1d-419e-a3d9-a04d4f165b3f.png)

![M `(M}M0G2T9)M3G2{DV7RF](https://user-images.githubusercontent.com/99183410/202596209-858ea713-d065-464e-8f4f-92714faae358.png)

**Comment by Happy2018new** [comment]
此存储库与用户中心及验证服务器没有任何关联。
请将此议题作为 `Not Plan` 关闭。

**Comment by LNSSPsd** [comment]
Network connection related, not related to this project.
