### ISSUE TITLE
Deprecate unmaintained `acme` and `lexport`

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#127]
As the original author of format `.mcacblock` (aka. acme) has been ruthlessly censored and blocked by NetEase Minecraft, We hereby sadly announce that `acme` feature will be deprecated and removed in future.

Parallel to this decision is the deprecation of `lexport` (Legacy `export` based on block data), at this stage we will just add deprecated notices in the program. Every user of those features should migrate to alternatives.

**Comment by Happy2018new** [comment]
此特性应当得到保留但不被维护，而不是删除吧

**Comment by Torrekie** [comment]
> 此特性应当得到保留但不被维护，而不是删除吧

just like how we drop .nbt format support, users never going to understand why we deprecating something problematic if we don't completely strip out them and make their pain ;)

**Comment by Happy2018new** [comment]
但这意味着用户先前的 `mcacblock` 文件将不能再导入。
对于那些曾使用 `AMCE` 导出建筑的建筑师们，它们或许如你所说，为此感到遗憾、叹息、甚至离去……

难道真的要剔除这个功能吗？为何必须这么做？
如何确实要这么做，能否详细说明一下 `mcacblock` 的文件格式，我万分感激(没学 go ，暂时看不懂源代码)

**Comment by Torrekie** [comment]
> 

we will push another announcement before we actually delete those features, for current stage we just print some warnings to let users know why they should use file formats that more advanced, beside that, we may probably release a structure format converter/parser in later future. But before we actually doing this, migration of commonly used file formats is still suggested.

**Comment by LNSSPsd** [comment]
Support for `lexport` may not be removed.

**Comment by LNSSPsd** [comment]
Whether to remove `acme` command should be reconsidered carefully, as removing it will not free a lot of space and this file format isn't as hard to process as `.nbt`.

**Comment by Torrekie** [comment]
users should migrate to other formats instead of those old ones, print out some warnings to encourage them to find alternatives

**Comment by LNSSPsd** [comment]
`lexport` is using the **legacy** trick but is not **old**.

**Comment by LNSSPsd** [comment]
The deprecation for `acme` has already completed by adding deprecation notice, and whether to remove the support should be considered later.
