### ISSUE TITLE
[bug] FB 版本更新检测出错

### ISSUE THREAD

**Issue by Inotart** [LNSSPsd/PhoenixBuilder#134]
# 错误的代码文件 fastbuilder\utils\utils.go
<img width="1013" alt="企业微信截图_16693993341070" src="https://user-images.githubusercontent.com/101685021/204036976-365a8ded-3219-4dbf-9283-e95224672153.png">
对于FB的失效部分,解决方案是更换链接为  https://api.github.com/repos/LNSSPsd/PhoenixBuilder/releases/latest 
下面是python的参考实现(链接部分过滤了开头的v)

![image](https://user-images.githubusercontent.com/101685021/204037118-c46fe93d-50fb-4d50-8e39-0b70e9bc14ff.png)
```python
import requests
def get_fb_version_internet():
    "从互联网获取FB的最新版本号"
    return requests.get("https://api.github.com/repos/LNSSPsd/PhoenixBuilder/releases/latest").json()["tag_name"][1:]
```

请尽快 通过链接映射或修改对应部分代码的部分 修复此 bug。
@LNSSPsd @Torrekie

**Comment by LNSSPsd** [comment]
COMMIT fe8b203
