### ISSUE TITLE
Failure reading strings whose length is greater than 127 bytes on exporting the data of command blocks

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [LNSSPsd/PhoenixBuilder#146]
导出时命令方块中含有titleraw，导入会出现：
命令方块中前面多一个符号，后面少一个符号，如下图所示：
-
原来的命令方块内指令：
![C431A3DC19F1E4AD0681168AA75DC8F3](https://user-images.githubusercontent.com/100061177/208088534-1395a573-5e3a-4df1-a835-4a13255a93fd.png)
-
导出再导入后：
![041D9FCE8E2712F76C8603D0DDBEE1BE](https://user-images.githubusercontent.com/100061177/208088549-79f5b404-1f38-4852-8efc-25b2f53e4cda.png)
前面多了一个□，后面少了一个}
正确重复导出再导入后，问题依旧。
第二次操作的控制台截图：
![~%ISF2RHRTK(~2}BY{BI0XL](https://user-images.githubusercontent.com/100061177/208088858-b4c1d1f0-a062-4b0d-ac53-ff160041fae9.png)

**Comment by Happy2018new** [comment]
看起来切割字符串的时候发生了一些错误

**Comment by Happy2018new** [comment]
常规的 `Tellraw` 命令无法正常复现此议题的错误，请尝试使用此命令复现其。
`titleraw @a[tag=女巫] title {"rawtext":[{"text":"§l§c你今晚毒害的是:§e"},{“score”:{"name":"女巫毒害","objective":"uidd"}},{"text":"§l§a号。"}]}`
