### ISSUE TITLE
-resume似乎坏掉了

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [LNSSPsd/PhoenixBuilder#158]
![KTRP(81)RIDH) J)BU 7~Z2](https://user-images.githubusercontent.com/100061177/210160607-09e4a715-c5fa-4dae-b984-15d5c5f90fdf.png)
此处的-resume在实际使用时无效果。
会提示跳过方块，但实际仍从0方块开始构建

**Comment by Happy2018new** [comment]
相关联的一个议题是 #84

**Comment by LNSSPsd** [comment]
840ad88e128f9d2a6ca1e5519ff6e92be76b50e5
