### ISSUE TITLE
无法解析机器人之名导致无法导入

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#169]
注明：以下内容提供自频道内的成员 `@频道成员-清风`
机器人名称：`清风不爱打方舟`
相关日志：

<img width="295" alt="image" src="https://user-images.githubusercontent.com/109064184/211154585-bc290366-8aeb-44fa-8166-98dade3569c7.png">

**Comment by Happy2018new** [comment]
应该是中文长度的问题，一个中文字符占两个，然后就 `bug` 了

**Comment by Happy2018new** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/109064184/211154770-4ab16ead-357c-492b-b69e-f65d30d3b018.png">

**Comment by LNSSPsd** [comment]
Fixed at ff57e86
