### ISSUE TITLE
Can we have an image format correction feature through ImageMagick?

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#17]
Go binding to ImageMagick: https://github.com/gographics/imagick

Users frustrated with input image formats since FastBuilder only support PNG. Let's use this to convert all non PNG inputs to PNG to silence their mouth.

**Comment by CMA2401PT** [comment]
I'm not sure, but if you are talking about "plot" function, maybe it has already been fixed? https://github.com/LNSSPsd/PhoenixBuilder/pull/7/commits/640913753b2bedbf8931b7c07ec9b7f4db5829d8
