### ISSUE TITLE
omega总是崩溃，是什么问题

### ISSUE THREAD

**Issue by mckyby** [LNSSPsd/PhoenixBuilder#174]
![Screenshot_20230109_132209_edit_125478974586977](https://user-images.githubusercontent.com/118090812/211245553-4802b00c-a7ea-47e3-9f46-55b82738ae05.jpg)

**Comment by LNSSPsd** [comment]
Compatibility works (chunk-related stuff) on NEMC 2.5.* haven't been done yet, and once it tries to deal with chunks it would surely crash. WIP notice has already placed for that.
