### ISSUE TITLE
Add default search paths

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#176]
We need something similar to `$PATH` but for user files which able to configure by conffiles. This can help users avoid entering full paths when attempting to load files downloaded from various sources

**Comment by LNSSPsd** [comment]
Using environment variables instead of configuration files may be better as dealing with those configuration files is really a complex thing

**Comment by LNSSPsd** [comment]
And it has already considered relative path, so one can run the program in the wanted path to use shortened form of path.
Declaring an extra path to be considered is somehow informal.
