### ISSUE TITLE
bdx的问题

### ISSUE THREAD

**Issue by ws19900518** [LNSSPsd/PhoenixBuilder#177]
使用PhoenixBuilder导出的bdx文件不可被omg解析 不管是lexport导出还是export导出

**Comment by Happy2018new** [comment]
请关闭这个议题，因为它并非是 `bug`

**Comment by Torrekie** [comment]
It might considered as a bug since there's parsing errors

**Comment by Torrekie** [comment]
Would you mind to provide some information for what problem you have described? Is there any runtime logs?

**Comment by Happy2018new** [comment]
导致的问题很简单，就是新加的 `op40` 没被支持，仅此而已

**Comment by ws19900518** [comment]
> 你介意提供一些关于你所描述的问题的信息吗？有运行时日志吗？
有 怎么发给你

**Comment by Happy2018new** [comment]
I plan to fix this bug on #167

**Comment by LNSSPsd** [comment]
Adding the support for a new operation should be a feature request.

**Comment by LNSSPsd** [comment]
Closed for the creation of #188
