### ISSUE TITLE
The Language files Line41 in fastbuilder/i18n Should Be Update to 2023,or not?

### ISSUE THREAD

**Issue by RainyHallways** [LNSSPsd/PhoenixBuilder#185]
[en_UK](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/en_UK.go) Line41:Copyright_Notice_Bouldev: "Copyright (c) FastBuilder DevGroup, Bouldev 2022",
[en_US](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/en_US.go) Line41:Copyright_Notice_Bouldev: "Copyright (c) FastBuilder DevGroup, Bouldev 2022",
[ja_JP](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/ja_JP.go) Line41:Copyright_Notice_Bouldev: "Copyright (c) FastBuilder DevGroup, Bouldev 2022",
[zh_CN](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/zh_CN.go) Copyright_Notice_Bouldev:"版权所有 (c) FastBuilder DevGroup, Bouldev 2022",
[zh_HK](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/zh_HK.go) Copyright_Notice_Bouldev:"版權所有 (c) FastBuilder DevGroup, Bouldev 2022",
[zh_TW](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/i18n/zh_TW.go) Copyright_Notice_Bouldev:"版權所有 (c) FastBuilder DevGroup, Bouldev 2022",

**Comment by Happy2018new** [comment]
我个人觉得，这是应该更新的（

**Comment by LNSSPsd** [comment]
That line is no longer being used anymore
