### ISSUE TITLE
VER4.9.96001 wasn't built successfully.But the newest version automatically updated

### ISSUE THREAD

**Issue by RainyHallways** [LNSSPsd/PhoenixBuilder#195]
[here's  the logs](https://github.com/LNSSPsd/PhoenixBuilder/actions/runs/3917695995/jobs/6697642912)

Error: io/commands/command_block_tweak.go:[28](https://github.com/LNSSPsd/PhoenixBuilder/actions/runs/3917695995/jobs/6697642912#step:26:29):19: d.NeedRedstone undefined (type *types.CommandBlockData has no field or method NeedRedstone)
make: *** [Makefile:159: build/phoenixbuilder-ios-static.a] Error 2
Error: Process completed with exit code 2.

**Comment by Happy2018new** [comment]
`NeedRedstone -> NeedsRedstone`

**Comment by RainyHallways** [comment]
> `NeedRedstone -> NeedsRedstone`

I see that and maybe [this](https://github.com/LNSSPsd/PhoenixBuilder/commit/32107149f283de6f476e49c0e3cbe65c3c94090d) change and forget to update the io/commands/command_block_tweak.go

**Comment by RainyHallways** [comment]
Thanks a lot
