### ISSUE TITLE
bdx文件读取问题

### ISSUE THREAD

**Issue by ws19900518** [LNSSPsd/PhoenixBuilder#199]
omg报错ERROR  无法从NBT: %v 获得命令方块数据 %v map[Command:/execute @a[tag=!Mark,c=1] ~~~ tag @s add Mark CustomName:段位系统，遍历检测，提升段位 ExecuteOnFirstTick:true TickDelay:0 TrackOutput:true auto:true conditionalMode:false id:CommandBlock] not command block

5.0.0PhoenixBuilder导入同样不能读取nbt

**Comment by ws19900518** [comment]
补充：之前能用的bdx现在也用不了 所以应该不是bdx问题吧

**Comment by LNSSPsd** [comment]
Use command `bdump` instead.
