### ISSUE TITLE
README Format && Bug Fix

### ISSUE THREAD

**Issue by RainyHallways** [LNSSPsd/PhoenixBuilder#228]
```md
<h1 align="center">PhoenixBuilder</h1>
<p align="center">
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/blob/main/LICENSE"><img src="https://img.shields.io/badge/License-AGPL%203.0-brightgreen.svg?style=flat" alt="LICENSE"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/releases"><img src="https://img.shields.io/github/v/release/LNSSPsd/PhoenixBuilder?display_name=tag&sort=semver" alt="Releases"></a>
  <img src="https://img.shields.io/github/stars/LNSSPsd/PhoenixBuilder.svg?style=falt" alt="Stars">
</p>
  
<p align="center">
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/issues"><img src="https://img.shields.io/github/issues/LNSSPsd/PhoenixBuilder.svg?style=flat" alt="opissues"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/issues?q=is%3Aissue+is%3Aclosed"><img src="https://img.shields.io/github/issues-closed/LNSSPsd/PhoenixBuilder.svg?style=flat&color=success" alt="clissues"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/pulls"><img src="https://img.shields.io/github/issues-pr/LNSSPsd/PhoenixBuilder.svg?style=falt" alt="oppr"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/pulls?q=is%3Apr+is%3Aclosed"><img src="https://img.shields.io/github/issues-pr-closed/LNSSPsd/PhoenixBuilder.svg?style=flat&color=success" alt="clpr"></a>
</p>
<p align="center">PhoenixBuilder is a multifunctional structure generating tool for Minecraft China Edition based on gophertunnel.
</p>
```
<h1 align="center">PhoenixBuilder</h1>
<p align="center">
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/blob/main/LICENSE"><img src="https://img.shields.io/badge/License-AGPL%203.0-brightgreen.svg?style=flat" alt="LICENSE"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/releases"><img src="https://img.shields.io/github/v/release/LNSSPsd/PhoenixBuilder?display_name=tag&sort=semver" alt="Releases"></a>
  <img src="https://img.shields.io/github/stars/LNSSPsd/PhoenixBuilder.svg?style=falt" alt="Stars">
</p>
  
<p align="center">
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/issues"><img src="https://img.shields.io/github/issues/LNSSPsd/PhoenixBuilder.svg?style=flat" alt="opissues"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/issues?q=is%3Aissue+is%3Aclosed"><img src="https://img.shields.io/github/issues-closed/LNSSPsd/PhoenixBuilder.svg?style=flat&color=success" alt="clissues"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/pulls"><img src="https://img.shields.io/github/issues-pr/LNSSPsd/PhoenixBuilder.svg?style=falt" alt="oppr"></a>
  <a href="https://github.com/LNSSPsd/PhoenixBuilder/pulls?q=is%3Apr+is%3Aclosed"><img src="https://img.shields.io/github/issues-pr-closed/LNSSPsd/PhoenixBuilder.svg?style=flat&color=success" alt="clpr"></a>
</p>
<p align="center">PhoenixBuilder is a multifunctional structure generating tool for Minecraft China Edition based on gophertunnel.
</p>

**Comment by LNSSPsd** [comment]
(Closed as completed)
