### ISSUE TITLE
将 `导入` 和 `导出` 中涉及到的 `方块数据值(附加值)` 迁移到 `方块状态`

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#244]
`Preview 1.19.70.21` 移除了 `setblock` 和 `fill` 命令对于 `数据值` 的支持，现在将只能填入 `方块状态` 字段。

具体内容见下。

<img width="394" alt="image" src="https://user-images.githubusercontent.com/109064184/216355115-26eb8508-3810-4841-970b-824fd42c4f2f.png">

***
因此，`PhoenixBuilder` 中涉及的所有 `导入` 和 `导出` 功能，其中的 `方块数据值(附加值)` 应该在此前迁移到 `方块状态`

**Comment by LNSSPsd** [comment]
No such need, a converter can do all the works
