### ISSUE TITLE
fill empty place with air option申请添加空气填充选项

### ISSUE THREAD

**Issue by HouKy2006** [LNSSPsd/PhoenixBuilder#248]
希望添加对建筑文件提供是否填充空白位置为空气的选项。

**Comment by Happy2018new** [comment]
这件事得在导出的时候完成才比较方便，因为 bdx 记录的可以看作一堆一堆的 `setblock` 命令，所以导入的时候再决定要不要导入空气的话，这不太现实……

**Comment by CMA2401PT** [comment]
考虑到空气的特殊性和占比，将其视为一堆setblock可能是不可行的

我个人建议是，对老的bdx文件直接遍历方块坐标（这很快）计算建筑体积，对于新文件添加一个meta字段（内为 json）描述建筑尺寸等可选信息，然后在导入时根据体积信息计算空气填充方法（fill）

即使如此，我也是比较反对处理空气方块的，因为其占比高的惊人
