### ISSUE TITLE
Omega群服互通，群发内容无法同步到游戏

### ISSUE THREAD

**Issue by kuang3** [LNSSPsd/PhoenixBuilder#269]
问题

**Comment by kuang3** [comment]
{
	"名称": "群服互通",
	"描述": "群服互通 游戏内可以看到Q群聊天，Q群也能看到服务器聊天",
	"是否禁用": false,
	"版本": "0.0.2",
	"来源": "Built-In",
	"配置": {
		"CQHTTP正向Websocket代理地址": "127.0.0.1:61974",
		"Q群消息格式化模版": "[groupName]:[QQUserName]:[msg]",
		"不要转发机器人的消息": true,
		"仅仅转发开头为以下特定字符的消息到QQ": "",
		"仅仅转发开头为以下特定字符的消息到服务器": "",
		"允许所有人使用这些指令": [
			"list"
		],
		"允许这些人透过QQ执行命令": {
			"XXXXXXXXX": true,
			"XXXXXXXXX": true
		},
		"只转发聊天消息": true,
		"向Q群发送玩家进出消息": true,
		"在控制台显示消息转发详情": true,
		"屏蔽其他群的消息": true,
		"屏蔽这些指令": {
			"spreadplayer": "呜呜呜"
		},
		"游戏内可以听到QQ消息的玩家的选择器": "@a",
		"游戏消息格式化模版": "[player]: [msg]",
		"链接的Q群": {
			"XX": XXXXXXXX
		}
	}
}

**Comment by kuang3** [comment]
cqhttp生成的device.json文件里面的登陆协议改成了protocol":2，绕过了登录扫描冻结，默认的无法登录

**Comment by Happy2018new** [comment]
这可能跟 `PhoenixBuilder` 没什么关系，这难道不应该是 `go-cqhttp` 库的问题吧？

话说，有没有可能就是，协议为 `2` 的那个登录方法还不支持这些功能（？

**Comment by kuang3** [comment]
> 
可是，默认的协议5已经无法登录账号了，只能走协议2的手表通道才能登录

**Comment by CMA2401PT** [comment]
好的，现在更新了内置的cqhttp，但是由于我没有安卓手机/windows电脑，而且新的cqhttp要求交互导致现在里面添加了不少workaround，双重debuff下，可能还是有问题，但是我没时间继续弄了. 总之，希望我足够走运，一次就蒙对了该怎么改吧。

**Comment by qixun233** [comment]
试着重新配置登录？

**Comment by kuang3** [comment]
![QQ截图20230327091025](https://user-images.githubusercontent.com/51186654/227817781-cdc8d845-b322-4a01-be6e-a237ef29dc10.png)
各位大佬，这是什么情况，无法登录了，前天还好好的，全删重新配置也是这个结果

**Comment by CMA2401PT** [comment]
删除cqhttp文件夹再试 ，可能是旧版本文件干扰了新版本工作

**Comment by Happy2018new** [comment]
建议：在本地配置好账号并确保可以发送消息后，把对应的 `device.json` 和 `session.token` 放到 `cqhttp_storage` 文件夹下。

**Comment by CMA2401PT** [comment]
按图示方法操作：

<img width="726" alt="截屏2023-06-15 13 14 05" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/97827666/ce5552d2-072d-4ea9-a537-86fa04f2d9bb">

**Comment by CMA2401PT** [comment]
feel free to reopen
