### ISSUE TITLE
Make FB/Omega Great Again

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#271]
随着fb/omega的功能日渐强大和丰富，以及越来越多的社区开发者参与和贡献代码，fb已经成为了一个有一定复杂性的项目。尽管f对项目的重构一直没有停止，但是现在的项目结构仍有诸多的不合理之处以及累积的问题。

因此，在 fb/omega 从一个成功迈向另一个成功之前，现在比任何时候都有必要对项目进行一次彻底的重构，并摆脱累积的技术负债。这次重构的目的是使项目内部的模块合理的解耦，重组织，在接口尽量不变的前提下修正已知的问题、设计的失误，并使代码易于阅读和扩展。

这个雄心壮志将从提交 50d856e 开始，并限制在 lib 和 solution 两个文件夹下。
目前，在这个提交中，已经实现了 micro omega 框架和 一个包含了单个基本组件的最小化 fb 客户端的实现，我相信这是一个好的开始。

roadmap 如下：
首先，omega 将被分为多个级别的实现：
1. micro omega (已经实现）:包含基本的数据包监听复用器/命令&数据包发送控制器。只涉及机器人的无需数据持久化功能（i.e. fb 现有的诸多功能）可以基于此实现
2.full omega: 包含micro omega所有功能、完整UQHolder、区块相关API、玩家相关API、菜单和交互API等功能
3.omega framework: 包含full omega所有功能和插件配置和启动功能，理论上和现有omega基本一致
然后，是整个迁移流程：
1. 实现omega框架
2. 将fb现有功能迁移到 micro omega 实现上
3. 修正现有的UQHolder造成的问题，并将现有的组件全部迁移到 omega framework 上

以上为提议草案

**Comment by Happy2018new** [comment]
我考虑把涉及会始终记录的数据的相关实现（例如记录的背包数据等）和涉及机器人公用资源的相关实现（例如记录已打开容器的数据、记录容器资源占用状态等）从 fastbuilder/bdump/blockNBT/API/ 迁移到 ResourcesControlCenter 下方

同时，UQHolder 中记录的其他一些数据，例如玩家列表、机器人当前所在坐标等，我认为理应随同迁移到 ResourcesControlCenter 下方，因为它们都属于公用资源的一部分，无论是资源所标识的数据（如本地库存数据）还是资源的占用状态（是否有人在使用背包等）。

也就是说，在顶层目录下新建文件夹 ResourcesControlCenter ，然后里面存放一些底层实现，用于存放机器人通过解析数据包所获得的数据，并掌管机器人的公用资源，如容器资源、背包资源等（同一时刻只能开启一个容器、在打开背包进行操作时，其他实现不能操作背包等）

接着，在 ResourcesControlCenter 中创建文件夹，作为基于 ResourcesControlCenter 底层实现的高级实现。
举个例子，底层实现只会提供一些读写物品操作请求的 api ，而高级实现就是在底层实现的基础上，去完成各种各样复杂的物品操作。

**Comment by Happy2018new** [comment]
也就是说，我个人认为 UQHolder 的其中一部分应该尽快删除，并使用另外一个东西来取代，并且服务于整个程序而不只是 Omega

**Comment by CMA2401PT** [comment]
那就让我期待一下你的api吧
顺便，现有的block nbt 中，很多地方都是把现有的代码又重复一遍，同时还存在（模仿一些现有的代码）的，似乎不甚合理的抽象。希望这次能看到一组简洁有力的接口和实现。

**Comment by Happy2018new** [comment]
> 那就让我期待一下你的api吧 顺便，现有的block nbt 中，很多地方都是把现有的代码又重复一遍，同时还存在（模仿一些现有的代码）的，似乎不甚合理的抽象。希望这次能看到一组简洁有力的接口和实现。

你说的重复代码应该说的是在放置方块实体的时候，每个方块实体都做了一个write datas之类的
这部分确实需要好好重写一下，

**Comment by Inotart** [comment]
好奇问一下这个的新框架是如何运行的

**Comment by Torrekie** [comment]
Let's create a new project instead, mark this repo as archived so we can avoid pulling bunch of git histories

**Comment by Inotart** [comment]
你好,我目前不在，如果你只是看到论坛邮件就不用回复了

**Comment by Inotart** [comment]
你好,我目前不在，如果你只是看到论坛邮件就不用回复了
