### ISSUE TITLE
OmegaSide on Windows每次启动都要下载Python解释器且都下载失败的问题

### ISSUE THREAD

**Issue by SuperScript-PRC** [LNSSPsd/PhoenixBuilder#276]
omegaside每次启动都会重复下载一次python的zip，但是每次下载得到的zip都是0KB，导致go报错 zip: not a valid file

**Comment by SuperScript-PRC** [comment]
第一次提示side/cache文件路径未找到，然后我在side\创建了一个cache文件夹。但仍有报错：
` ERROR  自动部署失败: zip: not a valid zip file
 ERROR  自动部署失败: zip: not a valid zip file
 SUCCESS  已经自动将Omega标准Python插件例子下载到 omega_storage/side/omega_python_plugins 中，你也可以将其他使用 Omega  标准 Python插件放入其中
 WARNING  开始自动部署 Python 插件开发和运行环境，根据你的网速，这可能要很久，但是放心，这仅会发生一次
 WARNING  无法在你的设备中自动准备Python解释器
panic: python not found

goroutine 107 [running]:
phoenixbuilder/omega/components/omega_side.(*OmegaSide).Activate(0x124befa0)
        phoenixbuilder/omega/components/omega_side/omega_side.go:201 +0x869
created by phoenixbuilder/omega/mainframe.(*Omega).Bootstrap
        phoenixbuilder/omega/mainframe/bootstrap.go:443 +0xb14

**Comment by SuperScript-PRC** [comment]
并且
side\Omega标准Python插件例子.zip
side\Omega运行相关库.zip

**Comment by CMA2401PT** [comment]
看起来是写权限的问题，换个目录也一样吗？

**Comment by CMA2401PT** [comment]
feel free to reopen
