### ISSUE TITLE
“成功连接到服务器”的提示消失

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [LNSSPsd/PhoenixBuilder#278]
在 `5.1.0` 版本的Phoenixbuilder中，成功连接服务器后的提示“成功连接到服务器”被删除了，导致用户无法通过控制台判断机器人是否已经进入游戏。
> ![image](https://user-images.githubusercontent.com/100061177/236607463-3428dc35-3665-4124-8cb2-755dc6bf195b.png)
此情况下机器人已经进入服务器，但无任何提示。

**Comment by RainyHallways** [comment]
[Canary5.1.00513](https://github.com/rnhws-Team/PhoenixBuilder/releases/tag/Canary5.1.00513)已经对其进行了修复

**Comment by RainyHallways** [comment]
应该是core.go的问题

**Comment by RainyHallways** [comment]
emm，5.0版本以前，fastbuilder把这段代码写进了gui版本的代码文件里（是与非gui通用的）然后最近删除这部分代码（
所以要修改就要去fastbuilder/core/core.go修改

**Comment by RainyHallways** [comment]
具体修复见 #282

**Comment by CMA2401PT** [comment]
complete
