### ISSUE TITLE
Request the collaborator access for this project

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#289]
Hi, @LNSSPsd @Torrekie @CMA2401PT @2401PT @CodePwn2021, all contributors of this project and all authorized sellers,
I'm sorry to bother you here, but please allow me to get the process states of this request.

In early January of this year, I requested the collaborator access for this project from FastBuilder Contributors channel. Over a longer period of time, I thought about asking about the progress of the matter, but I remembered that Ruphane told me not to ask any more, so I kept waiting. However, to this day, I have get none responded. So, now it's time for me to ask this!

I am writing some support for Bdump/BlockNBT for this project(PhoenixBuilder) now. And more, I write some code for advanced game interaction, you could see them [here](https://github.com/rnhws-Team/PhoenixBuilderBlockNBTLibrary).

Although my technique is not very strong, I think I can accomplish some simple functions.

That's all, and thanks!

June 12th, 2023 22:30 last edited by myself
June 12th, 2023 22:28 edited by myself

***

亲爱的 @LNSSPsd @Torrekie @CMA2401PT @2401PT @CodePwn2021 以及此项目的所有贡献者、所有的授权销售者：
很抱歉在此打扰你们，但请允许我在此询问此请求的处理进度。

在今年一月初，我在 FastBuilder Contributors 子频道请求此项目的协作者权限。较长的一段时间内，我一直考虑询问事情的进展，但我记得 Ruphane 说我不必再提了，所以我始终在等待回应。然而时至今日，我还没有得到任何回应。因此，现在是时候让我问问了！

现在我正在为此项目(PhoenixBuilder)编写一些 Bdump/BlockNBT 的支持。更多的，我正在写一些高级游戏交互的代码，你可以在 [这里](https://github.com/rnhws-Team/PhoenixBuilderBlockNBTLibrary) 看见它们。

虽然我的技术力不是很强，但我认为我应该可以完成一些简单的功能。

这就是全部了，谢谢。

2023年6月12日 22:30 最后由我自己编辑
2023年6月12日 22:28 由我自己编辑

***

<img width="297" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/f275cf43-2f3c-4fcf-b8cb-33de68a251a7">

**Comment by CodePwn2021** [comment]
帮你联系了，等他回复吧
后面频道见

**Comment by LNSSPsd** [comment]
https://github.com/LNSSPsd/PhoenixBuilder/invitations

**Comment by Happy2018new** [comment]
thanks
