### ISSUE TITLE
关于“结构空位”无法导入的问题

### ISSUE THREAD

**Issue by LegnaW** [LNSSPsd/PhoenixBuilder#297]
如题，bdump无法导入原版mc的结构空位方块。
起因是我在导入一个地皮文件的时候，发现一些结构的生成有误，经排查发现所有的结构空位均未被导入。

ps：个人导入时加了--nbt这一flag，不知道是否有关系但还是作为信息补充一下。

**Comment by Happy2018new** [comment]
`lexport` 基于 `mcstructure` 的，因此通过它导出的 `bdx` 不会包含 `结构空位` 。
但我并不打算让 `lexport` 扯上与 `区块` 相关的实现，因此你说的问题不在计划内。

或许你可以试试 `export` ，或者使用 `Omega Builder` 。
特别地，`export` 只会记录 `命令方块` 的数据；对于 `Omega Builder` ，目前会记录全部的数据，但截至现在，只有 `命令方块` 提供了 `NBT` 的注入支持。

**Comment by Happy2018new** [comment]
说错了，是 `Omega Reflector` 而非 `Omega Builder`

**Comment by Torrekie** [comment]
Maybe, implement an option `--detect-structure-void` is possible, scan every block in selected area for structure void and combine the result with mcstructure

**Comment by Happy2018new** [comment]
是的，可以尝试这么做，但这需要访问区块的数据，问题变得复杂。

**Comment by Happy2018new** [comment]
或者说，我们需要在请求结构数据的同时，再请求区块的数据，我的老天！

**Comment by Happy2018new** [comment]
如果某个方块是 `结构空位` ，那么其 `前景层` 和 `背景层` 均表现为 `-1` ，因此我通过这个规律来修复此问题，虽然可能会在一定情况下造成误判——但我们已经确保了获取 `mcstructure` 前检查了当前区域是否加载，发生错误的情况几乎不可能存在。

一个样例如下。
`packet.StructureTemplateDataResponse{StructureName:"mystructure:aaaaa", Success:true, ResponseType:0x1, StructureTemplate:map[string]interface {}{"format_version":1, "size":[]interface {}{1, 1, 1}, "structure":map[string]interface {}{"block_indices":[]interface {}{[]interface {}{-1}, []interface {}{-1}}, "entities":[]interface {}{}, "palette":map[string]interface {}{"default":map[string]interface {}{"block_palette":[]interface {}{}, "block_position_data":map[string]interface {}{}}}}, "structure_world_origin":[]interface {}{0, 0, 0}}}`
