### ISSUE TITLE
 feasibility study of block state <-> runtime id <-> legacy block

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#299]
it can be noticed that, the response of structure request contain block state and legacy block; and packet.SubChunk contains block runtime id. considering that currently we “guess” the matching of block state <-> legacy block because we only have the knowledge of block state <-> bedrock (1.19.0) runtime id (1.19.0) & nemc (2.25) runtime id <-> legacy block (2.25) mapping, using multimodal heterogeneous data source of same area may be helpful in obtaining the current mapping.

some difficulties are listed below:
. response of structure request contains two block while chunk data could have at most 256 layers in single block pos, currently we know nothing about their relationship
. we need to make sure they are actually describing the same block, this is a many to many matching problem, also, block could change between the arrival of two packets
. both structure request and sub chunk request could fail

it is a good time to cope with this challenge after the upgrade of rental server (a.k.a the time we need to upgrade fb) i think

**Comment by Happy2018new** [comment]
或许不用关闭它？
我曾计划过研究这个问题。
