### ISSUE TITLE
CurrentVersion Maybe Wrong？

### ISSUE THREAD

**Issue by RainyHallways** [LNSSPsd/PhoenixBuilder#300]
通过Motd发现网易最新的CurrentVersion为1.18.32
但PhoenixBuilder/minecraft/protocol
/info.go中CurrentVersion为1.18.30
请问是否有影响（
<img width="580" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/78735995/5486bd11-8ae3-473a-9934-752bafdcf624">

**Comment by CMA2401PT** [comment]
如果是按照 major.minor.patch 的规则来命名，大概是没有影响的

**Comment by Happy2018new** [comment]
但我们应该为此作出改变，虽然它在登录时所使用的是协议版本。

**Comment by CMA2401PT** [comment]
你没明白我的意思，如果是按照 major.minor.patch 的规则来命名，patch的改变并不会影响到api和接口，major.minor相同的时候是可以互相兼容的，只是修正内部的实现中的bug。然而MC的api和接口的内部实现与我们并没有什么关系，因为我们使用的是go语言的另一套完全不一样的实现，理论上我们只需要关注api和接口变化即可。

**Comment by Happy2018new** [comment]
你说的对，所以它本质上不会对程序运行产生影响，但我有强迫症（

**Comment by CMA2401PT** [comment]
如果你有强迫症的话，那么你反而应该选择1.18.30，而不是1.18.32，原因有二：
1. 我们实际上并没有做出任何针对minecraft（包）的修改，在没有修改的情况下提高版本号是没有道理的
2. 我去看了一眼我们使用的gophertunnel库，库的作者在1.18.30之后直接跳到了1.19.0，中间并没有1.18.32，鉴于我们实际使用的是他的1.18.30版本，我们应该尊重原作者的行为，并保持1.18.30版本号
因此我认为，除非遇到非得将版本号改为1.18.32否则就无法登陆的情况，否则我们应该和原作者使用相同的版本号

**Comment by Happy2018new** [comment]
看起来确实应该这么做，但请允许我用一个注释说明实际版本之间的差异，谢谢。

**Comment by CMA2401PT** [comment]
否则，我们就可能遇到这么一个情况：“嗨，你们将版本号从原作者的1.18.30提高到了1.18.32，那么你们改进/修正了什么呢？”，“不，我们什么都没修改，只是为了和一个愚蠢的网易版本号保持一致，虽然1.18.30没有任何问题”

**Comment by Happy2018new** [comment]
看起来已经不需要了，原作者的注释已经说明了问题。

**Comment by Happy2018new** [comment]
```
CurrentVersion is the current version of Minecraft as supported by the `packet` package.
```

**Comment by Happy2018new** [comment]
> 如果是按照 major.minor.patch 的规则来命名，大概是没有影响的

不过我看了下维基，在某些情况下即便 `major.minor` 相同，协议版本也仍在提升。

**Comment by Happy2018new** [comment]
就像这样

<img width="246" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/e43b9707-2c1f-4c2d-9e5d-02b497a6099f">
