### ISSUE TITLE
Wiki for this project

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#305]
我尝试做了一个简单的 Wiki 页面，你可以在 https://github.com/LNSSPsd/PhoenixBuilder/wiki 看到它。

这么做的目的主要有以下两个。
- `Bump Version` 前，利用它可以保存已经提交的更改，因此不必再等到 `Bump Version` 后再统一梳理版本更新日志，也方便了勘误之类的
- 用户中心有一些过时的文档，例如 https://fastbuilder.pro/phoenix.cn.html ，因此我想我们可以迁移其中一部分到此处？

当然，我个人希望该 Wiki 可以被任何人编辑（现在只有项目的协作者及仓库主可以编辑它），不知道 @LNSSPsd 和 @Torrekie 怎么想？

**Comment by LNSSPsd** [comment]
> 例如 https://fastbuilder.pro/phoenix.cn.html

No commercial documents in this project.

> 当然，我个人希望该 Wiki 可以被任何人编辑

I'm fine with that, restriction waived

**Comment by Happy2018new** [comment]
> > 例如 https://fastbuilder.pro/phoenix.cn.html
> 
> No commercial documents in this project.
> 
> > 当然，我个人希望该 Wiki 可以被任何人编辑
> 
> I'm fine with that, restriction waived

好的，用户中心的一些文档我会在相应的存储库创建 `PR`
