### ISSUE TITLE
Windows导入复杂问题

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [LNSSPsd/PhoenixBuilder#306]
在使用Windows版本的fastbuilder时，需要使用双斜杠
例如`C:\\Users\\23637\\Desktop\\fb\\12.29更新\\2.9更新文件\\Fox_and_Moon.schematic`
而不是`C:\Users\23637\Desktop\fb\12.29更新\2.9更新文件\Fox_and_Moon.schematic`
以至于每次都需要手动添加一个斜杠

复现步骤：用Windows导入即可复现

**Comment by Happy2018new** [comment]
此议题与它相关，因为该函数似乎对字符串进行了转义操作。

https://github.com/LNSSPsd/PhoenixBuilder/blob/d6aec624a7397deac8af5c6f848c3d8208a619f7/fastbuilder/parsing/parsing.go#L11

**Comment by Happy2018new** [comment]
一个可能的修复办法就是删除这段代码。

https://github.com/LNSSPsd/PhoenixBuilder/blob/d6aec624a7397deac8af5c6f848c3d8208a619f7/fastbuilder/parsing/parsing.go#L23-L26

**Comment by Happy2018new** [comment]
它看起来并不像一个 `Bug` ，而像是一个 `Request` ，因此我为此议题分配 `enhancement` 标签。

**Comment by LNSSPsd** [comment]
Windows' path scheme isn't human-friendly, and that's it. The path parsing system is an incomplete simulation of linux shell string, where escape characters apply.

**Comment by LNSSPsd** [comment]
Just use Linux path scheme, even in Windows.
e.g. `C:/Users/...`
