### ISSUE TITLE
有关无法在启动时正常解析 `args` 的问题

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#308]
这个问题似乎只存在于 `Windows` 下，因为当我尝试从 `Termux` 复现此问题时，一切表现正常。

这个问题表现为——当尝试在命令提示符使用诸如 `phoenixbuilder.exe --help` 时，`PhoenixBuilder` 会启动而不是打印帮助信息；同理，如果尝试使用 `phoenixbuilder.exe --omega_system` ，那么程序只会启动本体，而不会启动 `Omega` 。

@awaqwqa 已在他的 `Windows` 上复现了同样的错误。

我这边的环境是 `Windows 11 + Go 1.20.5` ，@awaqwqa 的环境我不是很清楚。

***
经过确认发现，是以下代码块 `Break` 了循环体，但我（因为没学 `C` 而）无法进一步跟踪并修复此问题。

https://github.com/LNSSPsd/PhoenixBuilder/blob/2b957118e2b79daa691ec0a0fd624217daa2417f/fastbuilder/args/args.c#L228-L230

**Comment by LNSSPsd** [comment]
Windows' `constructor` isn't provided with argument list, I guess

**Comment by Torrekie** [comment]
brutal fix, maybe we can insert a `getopt` implementation or use compat libraries for this

**Comment by LNSSPsd** [comment]
Libraries'd be much brutal
