### ISSUE TITLE
windows端问题(

### ISSUE THREAD

**Issue by awaqwqa** [LNSSPsd/PhoenixBuilder#311]
5.4.0版本的windows版本出现闪退情况 
无论是编译还是官方最新版本的release都是闪退（

**Comment by awaqwqa** [comment]
无任何报错（补充）

**Comment by LNSSPsd** [comment]
Run with `cmd` and see

**Comment by awaqwqa** [comment]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/88972629/4a7ec8c5-dd66-419c-8365-a17fba495087)
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/88972629/a733c9eb-0a84-48fb-9ecf-85b22ab555e5)

**Comment by awaqwqa** [comment]
嗯（

**Comment by Happy2018new** [comment]
```
Build Error: go build -o E:\Happy2018newの个人文件\GitHub\PhoenixBuilder\__debug_bin.exe -gcflags all=-N -l E:\Happy2018newの个人文件\GitHub\PhoenixBuilder\main.go
# phoenixbuilder/fastbuilder/args
args.c:23:2: warning: #warning "It seems that you're building PhoenixBuilder with plain `go build` command, it is highly recommended to use `make current` instead." [-Wcpp]
 #warning "It seems that you're building PhoenixBuilder with plain `go build` command, it is highly recommended to use `make current` instead."
  ^~~~~~~
# command-line-arguments
D:\Program\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\chenb\AppData\Local\Temp\go-link-370619136\000002.o: In function `parse_args_win32':
E:\Happy2018new�θ����ļ�\GitHub\PhoenixBuilder\fastbuilder\args/args.c:417: undefined reference to `__imp_timeBeginPeriod'
collect2.exe: error: ld returned 1 exit status (exit status 1)
```

**Comment by Happy2018new** [comment]
使用的是最新的提交构建的。

**Comment by LNSSPsd** [comment]
Link with -lwinmm.

**Comment by Happy2018new** [comment]
> Link with -lwinmm.

不会（

**Comment by LNSSPsd** [comment]
If you really do prefer `go build` instead of `make`, run with `CGO_LDFLAGS="-lwinmm" go build`.

**Comment by Happy2018new** [comment]
好吧，我不清楚该如何处理这个问题

**Comment by Happy2018new** [comment]
<img width="960" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/320f96f4-fa99-41cc-be4d-63ad3f8bdd69">

**Comment by LNSSPsd** [comment]
Windows environment directing sucks, let me make a workaround.

**Comment by LNSSPsd** [comment]
Try the latest commit.

**Comment by Happy2018new** [comment]
ok

**Comment by Happy2018new** [comment]
```
Process 9928 has exited with status 3221226356
```

**Comment by LNSSPsd** [comment]
OK, I'm debugging against that now.

**Comment by LNSSPsd** [comment]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/24724395/bc85e4e8-cc4b-42bc-a152-341c64bd61f0)
Looks like an invalid `LocalFree`.

**Comment by LNSSPsd** [comment]
Fixed in the latest commit.
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/24724395/2dcefb4f-e37c-4f85-81e7-147a3e7f77e9)

**Comment by Happy2018new** [comment]
问题已修复，修复在 6042dad 中。
***
<img width="960" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/e6a14e5c-926e-48fe-a444-8c9f65c10bf6">
