### ISSUE TITLE
Discussion against whether to remove `schematic` command

### ISSUE THREAD

**Issue by LNSSPsd** [LNSSPsd/PhoenixBuilder#312]
See 16c8da3 for discussion.

**Comment by CMA2401PT** [comment]
我们需要思考，如何找到一种行之有效的版权保护方法？

其中，一个无法绕开的问题是，如果一个（有版权的）文件被导入到一个租赁服，然后又被导出为一个新文件，这种情况该怎么办？

我的想法是，强制要求fb导入的每一个文件都有一个人声明为其来源负责（责任人）。其阻止盗版文件传播的原理是这样的：当某个文件被举报为盗版文件，注销责任人的账号，并在导入时检查文件是否有责任人，以及文件的责任人是否被注销。同理，当有人试图通过导入-导出的方式倒卖文件，也一并在此人被举报后注销其账号。

具体来说，其实现如下：当一个文件生成/声明责任人时，将文件的md5与生成者/责任人的密钥一并传至服务器，fb在导入每个文件前检查其md5对应责任人/生成者，如果此人被注销，则拒绝导入。
进一步的，我们可以将一个文件和导入密钥/允许导入人的信息传至服务器，以限制可以导入具有某个md5文件的人。

如果有必要，我可以提供服务器资源。

以上。

**Comment by Happy2018new** [comment]
就好比是百度不让你访问 Github.com 一样，我们不应该限制用户的自由。

**Comment by CMA2401PT** [comment]
是开源的，就像如果对chrome的限制感到不满，可以自己修改并使用chromium

**Comment by Happy2018new** [comment]
这样的话，它看起来应该被得到支持，只不过它会产生巨大的工作量，这是一件麻烦的事情。

**Comment by CMA2401PT** [comment]
是的，主要麻烦是在服务器端，需要做不少事。fb这边的事反而相对少一点，在导出时，把md5和用户凭据上传以绑定文件的责任人，在导入时上传文件md5以验证是否被举报/是否是倒卖狗负责的文件。最多再加一个声明对现有文件负责的小程序。麻烦的是服务器端。

**Comment by HouKy2006** [comment]
改变一个建筑方块，就会改变一整个文件的md5

**Comment by LNSSPsd** [comment]
There should be no discrimination against things proceeded for a tool.
For example, `gcc` should not break compiling a malware, as it is a compiler, and is intended to compile, instead of checking programmers' intends.

**Comment by LNSSPsd** [comment]
And it goes to be ironic when the compiler's author says, "due to the use of this compiler for compiling malwares, we have removed the function of compiling."

**Comment by CMA2401PT** [comment]
但是，gcc的使用并不需要使用者具有一个账号，或者连接验证服务器不是吗？

可以从这个角度入手，我们给用户提供的，是fastbuilder程序和配套服务。

我们可以这样想：Fastbuilder这个repo，是gcc，所有人可以自由的使用它。但是，我们提供给用户的，是编译好的fastbuilder和相关配套服务。正如gcc一样，我们可以不对fastbuilder做出任何限制，但是，可以对一并提供给用户的配套服务做出限制。

我们设计了一个阅读器，阅读器本身没有任何限制，但是，阅读器的联机服务可以是有限制的。

**Comment by LNSSPsd** [comment]
Structure building function isn't necessarily online in terms of the connection with authentication server.

**Comment by CMA2401PT** [comment]
是的，导入确实没必要连接在线服务。不过，如果这样理解这个问题：我们提供给用户的，不仅是导出建筑，而且也包括，保护自己（导出）的建筑版权（文件不被倒卖）这项“服务”，那么连接服务器是否也不是并没有道理呢？

**Comment by LNSSPsd** [comment]
> 而且也包括，保护自己（导出）的建筑版权（文件不被倒卖）这项“服务”

不包括，另外，本项目不属于 `服务` 范围。`服务` 仅限于 NEMC 服务器进入。

**Comment by CMA2401PT** [comment]
现在确实不包括这个服务，不过，如果有必要，我们或许可以添加这个服务。

**Comment by Torrekie** [comment]
for now my opinion is, don't provide schematic functionalities in our prebuilt binaries but do not strip out the code, which means users still able to build their own version that with schematic enabled

**Comment by Santino233** [comment]
目前来讲，bdx文件虽支持签名保证版权，而其他文件几乎不可能保障权益，并且bdx仍可以导入导出最后签上自己的大名，对此，我有以下建议：

首先，原创者需要懂得保护自身权益，多注意版权问题，留下水印等。其次，官方可以设置一个专项，在里面提交自己的原创作品并留下原创证据，保留版权。官方下发版权，导入时如果导入到已经拥有版权的文件需提供原创者提供的验证码才可导入，这虽然不能完美解决倒卖问题，但是可以基本解决当前的问题，倒卖是一个无底洞，永远也填不完。同时，完善举报系统，正式成功后给予严厉惩罚（强烈推荐封号）

以上纯属我个人观点，并未考虑到实际情况，若无法实行，请忽略本消息

**Comment by CMA2401PT** [comment]
那么，我们可以推出一种新的文件封装格式，这个格式包含了需要被导入的文件，以及，需要满足哪些条件才能被导入的信息。如果用户希望保护自己的文件权益，则可以使用这种新格式。同时，验证的手段也是写在这个文件，而非fb程序里。我想这样就可以在不与fb开放性、自由性冲突的前提下，保护文件的安全性。

**Comment by LNSSPsd** [comment]
> for now my opinion is, don't provide schematic functionalities in our prebuilt binaries but do not strip out the code, which means users still able to build their own version that with schematic enabled

I still cannot really accept with stripping out function for just the copyright-related theory.

**Comment by LNSSPsd** [comment]
Copyright isn't in consideration of this project at all.

**Comment by Santino233** [comment]
我们统一认为：此方法并不行得通，若实行之后很有可能出现更多售卖所谓的“schematicFB”漫天飞舞

**Comment by CMA2401PT** [comment]
这种新格式可以类似具有密码的rar文件，只不过更强大和复杂，以及更加自定义的解密方法，比如属性基加密，我想这应该和fb的设计不会产生冲突。

**Comment by LNSSPsd** [comment]
Good for y'all. Just do what y'all want.

**Comment by Santino233** [comment]
> 目前我的观点是，不要在我们的预构建二进制文件中提供原理图功能，但不要删除代码，这意味着用户仍然可以构建自己的版本，启用原理图。

我们统一认为：此方法并不行得通，若实行之后很有可能出现更多售卖所谓的“schematicFB”漫天飞舞

**Comment by LNSSPsd** [comment]
> > 目前我的观点是，不要在我们的预构建二进制文件中提供原理图功能，但不要删除代码，这意味着用户仍然可以构建自己的版本，启用原理图。
> 
> 我们统一认为：此方法并不行得通，若实行之后很有可能出现更多售卖所谓的“schematicFB”漫天飞舞


Good for y'all. Just do what y'all want.

**Comment by Torrekie** [comment]
如果不是担心被找事，谁关心fb被拿来干什么了啊，要我说直接把fb搞成会员制好了

**Comment by HouKy2006** [comment]
> 

这样才最好，FB有点失之本心了

**Comment by Santino233** [comment]
我有些不理解，所谓“会员制”该如何执行？

**Comment by Torrekie** [comment]
由已有的用户进行邀请，最初的已有用户可以是contributor或者……抢购的名额？有待商榷

**Comment by CMA2401PT** [comment]
我来向后来人概括一下现在遇到的困境（可能有错或者不太准确）：

如果你做了这件“好事”，你实现这个“好事”的“过程和方法”违背了你的“信仰”，因此，你得“下地狱”

如果你做了这件“保护文件所有者/创建者权益”，你实现“保护文件所有者/创建者权益”的“目前能想到的过程和方法（必须有一个验证服务器提供服务/限制）”违背了你一直追求的信仰“开源精神”，因此，你得“下地狱（与自己的追求背道而驰）”

因此，问题的关键应该是，有什么方法，可以在不违反开源精神的同时，保护文件所有者/创建者权益

**Comment by Happy2018new** [comment]
或许我们不对功能进行任何改动，我们只是在每次启动时告诉用户，你应该做什么，你不应该做什么，以及做了这些事情后，会发生什么。

**Comment by Santino233** [comment]
总之，我保持恢复schematic文件导入的功能，或许我们可以在新注册用户进行筛选？

**Comment by Santino233** [comment]
> 或许我们不对功能进行任何改动，我们只是在每次启动时告诉用户，你应该做什么，你不应该做什么，以及做了这些事情后，会发生什么。
> 
> 至于用户怎么做，我们无权干涉，我们只是做一个建议的人，让用户自己来维护社区的和谐性，虽然不大可能。
> 
> 就像烟盒上面贴的"吸烟有害健康"那样，用户可以选择继续吸烟，然后获得肺癌。
> 
> 但这里考虑的是另外一件事，有些人希望得肺癌，而他们得了，我也要得，而我不希望得肺癌。

我比较赞同此说法，但是我们或许可以略微添加一些管制呢？例如发现倒卖问题后一并讲证据投递于官方邮箱
