### ISSUE TITLE
We are terminating the use of `schematic` format in PhoenixBuilder releases

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#313]
**If you have been directed here from a PhoenixBuilder warning, you might want to take actions at this stage. Something is currently expected to break since version 5.4.0, and a full solution will be implemented after we find a way to resolve current controversy. You can still have all unlimited features in `libre` branch but we cannot restore them to `main`**

**如果您被PhoenixBuilder的警告重定向至此，您可能想要采取一些措施。某些东西目前被计划自版本5.4.0起报废处理，在我们找到解决当前争端的合适方法之前，这个问题将无法得到完整解决**

***

<details>
  <summary>English</summary>
Recently we have received plenty of complaints from community content creators regarding to the paid redistribution of unauthorized contents by taking advantages of file parsing/reproducing feature provided by PhoenixBuilder. In consideration of the protection of the rights and interests of content creators, we terminated the support for format <code>schematic</code> and <code>mcacblock</code>.

Related functionalities **WON'T** be restored before we found any proper way to protect community content creators in a better place.

To clarify, PhoenixBuilder only provide features of constructing Euclidean geometry shapes and structure file parsing/reproducing for Minecraft, violating other people's intellectual property content is the user's personal behavior, PhoenixBuilder and Bouldev should not and never be responsible regarding to this, just as users downloading pirated books has nothing to do with the e-reader itself.

We (Bouldev and contributors of this project) are willing to do everything in our power to prevent such incidents from happening.
</details>

<details>
  <summary>简体中文</summary>
近期我们收到大量社区内容创作者的反馈，一些用户试图通过PhoenixBuilder的文件读取功能来有偿进行未经授权内容的再分发，出于对创作者权益保护的考量，我们中止了对<code>schematic</code>与<code>mcacblock</code>文件格式的支持。

在我们找到更好地保护社区内容创作者的方式之前，有关的功能将**不会被恢复**。

需要声明的是，PhoenixBuilder仅提供在《我的世界》中进行欧几里得几何的建造以及结构文件的读取/复现功能，对他人的知识产权内容进行盗录为用户的个人行为，与PhoenixBuilder及Bouldev无关（正如用户下载盗版书籍与阅读器本身的无关性）。

但是，我们（Bouldev以及项目贡献者）愿意尽我们所能来阻止此类事件继续发生。
</details>

**Comment by LNSSPsd** [comment]
Unsolved Conflict #312

**Comment by LNSSPsd** [comment]
Refer to [la Branche de Liberté](https://github.com/LNSSPsd/PhoenixBuilder/tree/libre) if desired to use these formats.
