### ISSUE TITLE
[WIP] try to (re-)enable omega running in a remote manner.

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#317]
at first, i try to directly read and write packet **bytes** with minecraft.Conn but ends up fail. though the remote omega can communicate with client, something inside minecraft.Conn seems become very unstable and i cannot figure out how i broken the origin design schema.
currently i write a very ugly support of remote omega, i promise 'l clean up these mess ASAP

**Comment by CMA2401PT** [comment]
add44dd9b0d0f3f7173d06527b52d9a13dca34af

**Comment by Torrekie** [comment]
CI fails many times, you might want to do a local compile check first and commit changes as PR

**Comment by CMA2401PT** [comment]
my fault，local compile succeed but some changes are not correctly comitted

**Comment by CMA2401PT** [comment]
see #319
