### ISSUE TITLE
packets decode 

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#318]
seems that we forget this d652636e193d5c29568f6686ca9ffb9cb469bcfb , need fix?

**Comment by Happy2018new** [comment]
#189 似乎在曾经讨论过这个问题？

**Comment by Happy2018new** [comment]
暂时性的回退了这个修改，因为这会产生大量的错误日志，就像这样

**Comment by Happy2018new** [comment]
![29f129464f13088b](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/8a905f0c-dbca-4465-9246-684661323413)

**Comment by LNSSPsd** [comment]
> seems that we forget this [d652636](https://github.com/LNSSPsd/PhoenixBuilder/commit/d652636e193d5c29568f6686ca9ffb9cb469bcfb) , need fix?

Nope, it's like that from the first version of PhoenixBuilder.
