### ISSUE TITLE
about remote omega and the reason of instability

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#319]
在 ab6749852a89f51dd5e73a975538067a62792913 中，我试着为neomega添加了远程接入服务器的支持。一个程序（access point）连接到mc服务器后，打开网络端口，并允许其他程序（endpoint）中的neomega通过它间接与服务器交互。
首先我想说明一下这么做的意义，显而易见的，当我们想测试代码时，可以立刻获得结果，而不必每次测试时都忍受痛苦的进入服务器过程。同时，这也使整个重新加载所有插件而不退出服务器变得非常容易。

然而，现在遇到了一些问题，其原因还没搞清楚

首先，需要说明的是，end point 通过 access point 进行游戏数据包收发的两种方式：
收：
1. access point 直接从conn中读出数据包的原始字节(ReadPacketAndBytes)并直接将其发送到end point，我们称之为direct pub/sub 模式
2.  access point 从conn中读出数据包(ReadPacket)，再次将其序列化后发送到end point，end point将其反序列化。
同理，发送也有这两种方式，直接发送数据包原始字节和先把包序列化，反序列化再发送。

经测试，发送似乎没问题了，无论是否是direct模式，然而，接收的direct 模式似乎存在问题，一些数据包无法被正确读出，而且问题只在部分数据包类型中出现。

如果希望复现问题，请将 access_point 的 directPubMode改为true, handler的directSubMode改为true

我感觉，这个问题似乎是来自于ReadPacketAndBytes，因为这个孔的实现很粗暴，不能排除可能某些数据在底部是共享/脏的可能性，而且没有看到锁操作。

如果有人可以帮我分析一下这个问题，那么非常感谢。

**Comment by CMA2401PT** [comment]
fixed

**Comment by LNSSPsd** [comment]
Better to avoid listening `0.0.0.0` I think, could be better using an unix socket.

**Comment by CMA2401PT** [comment]
> Better to avoid listening `0.0.0.0` I think, could be better using an unix socket.

sure, now use ipc:// instead (m afraid that unix:// is not supported in windows, however ipc:// will create files)

**Comment by LNSSPsd** [comment]
> > Better to avoid listening `0.0.0.0` I think, could be better using an unix socket.
> 
> sure, now use ipc:// instead (m afraid that unix:// is not supported in windows, however ipc:// will create files)

Real IPCs would be better.
References for that:
[IPC via Pipes, Linux, Stackoverflow](https://stackoverflow.com/questions/43412316/interprocess-communication-via-pipes)
[IPC Pipes, Win32 API](https://learn.microsoft.com/en-us/windows/win32/ipc/pipes)
