### ISSUE TITLE
it's horrible, I think we need to fix this

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#323]
see 005594fe1e3ba9be2fbb48567a7ee1ea35659517

in client.GetToken(username string, password string), the username is actually not username but just an empty string, while the password should be a json string which contains both username and password. it's horrible

**Comment by LNSSPsd** [comment]
We can rename `password` to something like `temp_token`

**Comment by LNSSPsd** [comment]
Refer to #331.
