### ISSUE TITLE
无法正常检测更新的问题

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#324]
如题，当使用 `5.5.0` 时不会提醒应该强制升级到 `5.5.1` 。
已知此问题发生在 a3087951132ee76ef8085dc5e2a3a53b78545ebb 之后的版本中，但我这边不方便复现和修复，固提起本议题。

<img width="488" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/4bda81e4-00d2-4a64-a39b-b0a766f6804c">

**Comment by Happy2018new** [comment]
奇怪的是，当我在 `go build` 下添加图中 `47` 行的代码时，一切运作正常。

<img width="960" alt="image" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/a8a761bb-bf43-4fbd-8f80-ab65a0a09f2f">

**Comment by Happy2018new** [comment]
我大概知道了，我跑到 `Termux` 去 `make` 了一下，打印出来的 `args.FBPlainVersion` 不包含 `v` 这个东西

**Comment by LNSSPsd** [comment]
`^v?` would work in that case

**Comment by Happy2018new** [comment]
> `^v?` would work in that case

这个问题以及修复了，在删除了 `^v` 后。

**Comment by Happy2018new** [comment]
主要是 `Windows` 不能 `make` ，所以复现起来不太方便。

**Comment by LNSSPsd** [comment]
> > `^v?` would work in that case
> 
> 这个问题已经修复了，在删除了 `^v` 后。

Don't do that! It'd make github version numbers invalid!

**Comment by Happy2018new** [comment]
> > > `^v?` would work in that case
> > 
> > 
> > 这个问题已经修复了，在删除了 `^v` 后。
> 
> Don't do that! It'd make github version numbers invalid!

but, why?

**Comment by RainyHallways** [comment]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/78735995/caa34784-ca31-4ff9-beb3-c9b5ffb4b4ed)
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/78735995/f857fe02-36bd-4aa0-8591-27e1543455e9)

**Comment by LNSSPsd** [comment]
`^v?((\d+).(\d+).(\d+))$`'d be the BEST.
( ^ Not escaped tho)

**Comment by Happy2018new** [comment]
![Screenshot_20230707_224610](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/8db2d05b-c849-41a3-b1ea-20297dd9fe25)

**Comment by Happy2018new** [comment]
看起来没什么问题，如果直接删除 `^v` 。

**Comment by RainyHallways** [comment]
args.FBVersion did not exsit "v"

> `^v?((\d+).(\d+).(\d+))$`'d be the BEST, where you make sure the WHOLE string is under consideration. (Not escaped tho)

args.FBVersion did not includ "v"

**Comment by LNSSPsd** [comment]
`?` makes `v` optional

**Comment by LNSSPsd** [comment]
And `^` ensures the whole string is considered

**Comment by Happy2018new** [comment]
那么请通过暴力推送抹除我的提交吧，它不太合适，趁现在。

**Comment by Happy2018new** [comment]
或者我自己来做这件事情吗？

**Comment by RainyHallways** [comment]
version_regexp := regexp.MustCompile("^v?((\\d+).(\\d+).(\\d+))$")

**Comment by Happy2018new** [comment]
oh，剩下的交给 `Ruphane` 来完成吧。

**Comment by Happy2018new** [comment]
> oh，剩下的交给 `Ruphane` 来完成吧。

算了，还是让我做吧。

**Comment by Happy2018new** [comment]
注：真正的修复位于 6486320 中。
