### ISSUE TITLE
Replace WebSocket-based APIs with HTTP API

### ISSUE THREAD

**Issue by LNSSPsd** [LNSSPsd/PhoenixBuilder#331]
The new API is going online in a few days, and the WebSocket-based FBUC api, along w/ the `Node.JS` based second backend, would all be deprecated.

**Comment by LNSSPsd** [comment]
New API:

```
"/api/phoenix/login",
			std::optional<std::string>, login_token, "login_token",
			std::optional<std::string>, _username, "username",
			std::optional<std::string>, _password, "password",
			std::string, server_code, "server_code",
			std::string, server_passcode, "server_passcode",
			std::string, client_public_key, "client_public_key"

"/api/phoenix/transfer_start_type",
			std::string, content, "content"

"/api/phoenix/transfer_check_num",
			std::string, data, "data"

```

**Comment by LNSSPsd** [comment]
Refer to c70a294d0abc61182641ed26fc733f9a94479e8a

**Comment by CMA2401PT** [comment]
Refer to 02cd07b0d6128ae24f362635b1dc1b81cb0dd970 2272a75b71fc7c00bd062d94f94e932ea83acba2 5ed9fe872ac1bf48f06866e2eca775ee4d823bf5 this should be fix

however, 
1. in client.Auth username and userpassword login dose not function properly, server just return "Invalid token" error
2. request should not contain username&userpassword when there exist usertoken, or server will response "conflict token", refer to 5ed9fe872ac1bf48f06866e2eca775ee4d823bf5 in main branch 
3. in user center, get token button just return an 404 page

综上所述，如果没有在本地保存过token现在用户无法登陆，因为服务器无法正确处理账号密码登陆请求，又无法从用户中心下载自己的token

**Comment by CMA2401PT** [comment]
fixed, refer to 5edb639c007841ed8f587e90c1c61de3136bd26c and 3c051f983f05a523cc2ff0a9744c9b0797f89fa4

**Comment by CMA2401PT** [comment]
看起来似乎没有问题了，大概

**Comment by LNSSPsd** [comment]
Many thanks

**Comment by CMA2401PT** [comment]
currently i cannot commit directly to libre branch, so a pr is made: #333

**Comment by Happy2018new** [comment]
> currently i cannot commit directly to libre branch, so a pr is made: #333

它们已通过 `cherry-pick` 提交，详见 https://github.com/LNSSPsd/PhoenixBuilder/commit/1aca07a7e1594d3ae4c53ce258c4c7039bd0faff

**Comment by Happy2018new** [comment]
稍后 `libre` 将被 `Bump Version` ，`libre-a` 将被删除。
