### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by RainyHallways** [LNSSPsd/PhoenixBuilder#338]
- [ ] Sweep the community environment
- [ ] Unsupport for the panel provider
- [ ] Isolate developers from users
- [ ] Change some APIs in some easy-get platform

---

That's all for now.

**Comment by Happy2018new** [comment]
我并不赞成放弃或删除 `Android` 和 `Windows` 的兼容，原因有以下几点。

1. 我主要在 `Windows` 开发此项目。
2. `Windows` 不能使用 `make` 编译这个项目，因此部分特殊情况下为了 `Debug` ，我会在 `Termux` 使用 `make` 命令

所以无论如何也不应该删除对它们的支持。

而且我得说，这是治标不治本的行为，社区可能真的需要有人帮帮忙。

**Comment by RainyHallways** [comment]
> 我并不赞成放弃或删除 `Android` 和 `Windows` 的兼容，原因有以下几点。
> 
> 1. 我主要在 `Windows` 开发此项目。
> 2. `Windows` 不能使用 `make` 编译这个项目，因此部分特殊情况下为了 `Debug` ，我会在 `Termux` 使用 `make` 命令。
> 
> 所以无论如何也不应该删除对它们的支持。
> 
> 而且我得说，这是治标不治本的行为，社区可能真的需要有人帮帮忙。

I've edit it.

**Comment by Happy2018new** [comment]
ok, I see
