### ISSUE TITLE
libre分支问题

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [LNSSPsd/PhoenixBuilder#339]
release中的libre分支也不能使用schem -p、acme -p
![4e05cae2fc43eb05481c5d1336d8d5ef](https://github.com/LNSSPsd/PhoenixBuilder/assets/100061177/050d627f-a93b-43eb-a23d-98868c3b478a)
![7d57578cb4cb00951572dd8c66bf47b6](https://github.com/LNSSPsd/PhoenixBuilder/assets/100061177/d75738da-a138-4f38-b77c-126418c0e167)
可以看到执行没反应

**Comment by Happy2018new** [comment]
此功能在 3ed4e3b 被重名为 `schematic` ，现在请使用 `schematic -p <path>` 来调起此功能。

详见 https://github.com/LNSSPsd/PhoenixBuilder/commit/3ed4e3b78d4f0b9647ff58dbb65f850669b4918e#diff-6adc587334ffb1b938ced9793895de0af448b0e006cefd3e44443a0c3918656aR16
