### ISSUE TITLE
最新5.7.2的ish版本的PhoenixBuilder无法运行

### ISSUE THREAD

**Issue by banmenglive** [LNSSPsd/PhoenixBuilder#344]
![IMG_0514](https://github.com/LNSSPsd/PhoenixBuilder/assets/123043043/696e3060-e5c5-40a7-a69b-335b322f546d)
我的设备是iPhone 6s ios版本15.7.7

**Comment by Torrekie** [comment]
need detailed crash logs, could you retry with `gdb` or `catchsegv` too help us to locate bugs?

**Comment by LNSSPsd** [comment]
Could be related to [`args.c`](https://github.com/LNSSPsd/PhoenixBuilder/blob/main/fastbuilder/args/args.c).
