### ISSUE TITLE
New User Manual

### ISSUE THREAD

**Issue by 4801XP** [LNSSPsd/PhoenixBuilder#355]
I made the changes myself, added a small amount of Chinese explanations, and updated some instructions
[用户手册.txt](https://github.com/LNSSPsd/PhoenixBuilder/files/13624045/default.txt)

**Comment by Happy2018new** [comment]
我曾经留存了这个文档的原始形式，它位于[此处](https://github.com/rnhws-Team/FastBuilderWebsite-Achive/blob/main/phoenix.cn.md)。

你应该从[该文档](https://github.com/rnhws-Team/FastBuilderWebsite-Achive/blob/main/phoenix.cn.md)修改，而非从网页上复制这一切然后再修改，这会使得部分文本格式被丢失。

由于 _bouldev/FastBuilderWebsite_ 的删除，我现在无法再追踪到这个文档的地址——否则我会你应该前往正确的存储库修改这则文档。我猜测，这则文档现在可能位于一个尚未公开的存储库中？ _[需要验证]_

**Comment by 4801XP** [comment]
我会在office word中尝试还原字体和文本格式

**Comment by Happy2018new** [comment]
> 我会在office word中尝试还原字体和文本格式

你可能理解错了，这个文档是基于 `Markdown` 来渲染的，所以你不应该使用 `Word` 来还原字体和文本格式。

**Comment by Happy2018new** [comment]
下面是一个例子。
***
原始文本
```
> 你好
> **你好**
> _你好_
```
***
渲染结果
> 你好
> **你好**
> _你好_

**Comment by 4801XP** [comment]
我明白了
