### ISSUE TITLE
.md为后缀的用户手册

### ISSUE THREAD

**Issue by 4801XP** [LNSSPsd/PhoenixBuilder#356]
[用户手册.md](https://github.com/LNSSPsd/PhoenixBuilder/files/13627699/default.md)

_Note - This issue related to #355 [Added by @Happy2018new ]_

**Comment by Happy2018new** [comment]
你好像弄错了什么？
你应该复制[这里](https://[raw.githubusercontent.com/rnhws-Team/FastBuilderWebsite-Achive/main/phoenix.cn.md](https://raw.githubusercontent.com/rnhws-Team/FastBuilderWebsite-Achive/main/phoenix.cn.md))的文本然后进行修改……

**Comment by 4801XP** [comment]
404

**Comment by Happy2018new** [comment]
> 404

现在应该没问题了

**Comment by 4801XP** [comment]
还是404

**Comment by Happy2018new** [comment]
> 还是404

可能你网有问题

**Comment by 4801XP** [comment]
能看到了

**Comment by Happy2018new** [comment]
此议题已超过 `90` 天未得到回应，因此现将其作为 `未计划` 而关闭。
你仍然可以通过创建新的议题以使该议题描述的请求得到关注。
