### ISSUE TITLE
get功能无法正常使用

### ISSUE THREAD

**Issue by Wuxie233** [LNSSPsd/PhoenixBuilder#361]
如图
<img width="867" alt="e501946e58a869dcd021c2f5b5466f79" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/121599346/23b5b004-e57f-4333-9e92-46e9af0edada">
使用get后 返回No position got. (ignorable)
（辅助用户已绑定主人，且此功能在游戏版本1.20时仍可使用）

**Comment by Wuxie233** [comment]
We really need this function!!!

**Comment by Happy2018new** [comment]
该功能在启用选项 `skip-mcpc-check-challenges` 时不可用，因为启用 `skip-mcpc-check-challenges` 时，命令请求的底层实现是 `魔法指令`，这导致仅通过 `execute @a[name=xxx] ~ ~ ~ testforblock ~ ~ ~ air` 的方式无法得到玩家的坐标数据。

需要注意的是，`skip-mcpc-check-challenges` 只是一个实验性的替代方案(用于缓解版本错误)，但就现在而言，你可以去掉这个选项，版本错误不会发生。

**Comment by Happy2018new** [comment]
当然，可能实际上不是我猜的这个原因……？

**Comment by Happy2018new** [comment]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/53c2b535-f593-4d0f-bfc9-fb0a0dfcb445)

**Comment by Wuxie233** [comment]
Sorry, I still don’t quite understand. So, is this situation a bug or an issue on my end?

**Comment by Happy2018new** [comment]
如果你使用的是第三方验证服务，那么这个错误会永远出现，除非这些验证服务允许你设置主人的名称。

**Comment by Wuxie233** [comment]
我稍后尝试一下使用官方的验证服务（咕咕酱的验证服务有提供主人绑定的功能 我已经绑定了 但是仍然不可用 所以这个可能需要咕咕那边适配？）

**Comment by Happy2018new** [comment]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/109064184/7da102c6-fb3d-4aea-8c9d-71ba36d6998d)

**Comment by Happy2018new** [comment]
**为了避免因误绑定而造成损失，游戏ID自动绑定功能已被移除。**

**Comment by Wuxie233** [comment]
在这个公告发出前，get也无法使用

**Comment by Happy2018new** [comment]
你可以将你的 Token 在 QQ(3527679800) 上发送给我(当然也请附带上你的租赁服号)，然后我去看下咕咕那边返回的东西长什么样。

如果你认为我这是诈骗行为，你可以选择拒绝。

**Comment by Wuxie233** [comment]
我尝试了fb官方验证服务，仍然不行
<img width="867" alt="7ff53f4486561b11444086b3c37eb184" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/121599346/138788d2-9161-415b-904a-795fc31088b7">
![f551fb269cfd7c6a37c56bef798456bd](https://github.com/LNSSPsd/PhoenixBuilder/assets/121599346/8d33212e-f907-4c4f-b92d-78ddeb06bdff)
<img width="990" alt="9996137450fef27c6489c34fb6be1f99" src="https://github.com/LNSSPsd/PhoenixBuilder/assets/121599346/1c522a35-63bf-4f6c-84de-f2d4698ab42f">

**Comment by Happy2018new** [comment]
奇怪……

**Comment by Wuxie233** [comment]
等一下 我犯了个大错 我没有给fb官方验证服务器的机器人op权限 再我给予fb官方的机器人op权限后 get可以正常工作了

**Comment by Wuxie233** [comment]
但是咕咕的验证服务器仍存在get无法使用的问题（有op权限且已经绑定）

**Comment by Happy2018new** [comment]
已通过 `QQ` 沟通解决。

结果：
`https://liliya233.uk` 处的验证服务器由于不存在 `respond_to` 参数来传递主人的名称，因此不支持 `get` 功能。
此议题按 `未计划` 关闭

**Comment by Liliya233** [comment]
已添加此配置项: `用户菜单 -> 游戏名`
