### ISSUE TITLE
从 Releases 下载的可执行文件 `Windows-x86` 每次启动都提示 `Failed to contact with API`

### ISSUE THREAD

**Issue by SuperScript-PRC** [LNSSPsd/PhoenixBuilder#364]
![image](https://github.com/LNSSPsd/PhoenixBuilder/assets/112140997/1e7bea2a-b777-4b17-9fe2-158115f4222e)
 - System: Windows 11
 - File: phoenixbuilder-windows-executable-x86.exe
 - Version: 0.6.2
 - VPN: No

**Comment by Happy2018new** [comment]
Confirmed, but I don't know how to fix it, may @CMA2401PT help this?

**Comment by CMA2401PT** [comment]
x86_64 and x86 is very different in many aspects, e.g. int in 32bit is int32, but is int64 in 64bit. i suggest dropping 32bit version support

**Comment by Happy2018new** [comment]
I'm not sure about this.
Should we drop winodws/x86 support on PhoenixBuilder? @Torrekie

**Comment by Torrekie** [comment]
i can't see any useful information from this log, I guess this was some size problems in our C codes. But dropping windows-x86 is ok I guess

**Comment by Happy2018new** [comment]
Ok, let us do that.

Closed this as completed. _[ 3b30fd7 ]_
