### ISSUE TITLE
#mark nm，我有无数小号，你mark一次，block一次，我issue一次

### ISSUE THREAD

**Issue by Hky-Des** [LNSSPsd/PhoenixBuilder#49]

**Comment by CMA2401PT** [comment]
@LNSSPsd  把项目改成private吧，既然免费的源代码不想要那以后也别要了

**Comment by Hky-Des** [comment]
auth只有共钥，且没有服务端。算哪门子的开源呢？

**Comment by LNSSPsd** [comment]
> auth只有共钥，且没有服务端。算哪门子的开源呢？

PhoenixBuilder 并非仅仅面向 Minecraft 中国版的程序，其面向一般版 Minecraft 的支持并不需要验证服务器的存在，故仅在中国版中的使用是收费的。

另外，面向国际版的支持已经在计划当中，具体可见于[Projects/TODOs](https://github.com/LNSSPsd/PhoenixBuilder/projects/1)。

此外，希望您能避免辱骂性的语言冷静讨论。

**Comment by LNSSPsd** [comment]
Closed, add comments to issue #50 instead of this one.
