### ISSUE TITLE
CI build.yml messed up GUI and CLI files

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#53]
The recent update of it has corrupted the uploading process
phoenixbuilder (Linux x86_64), phoenixbuilder-android-arm64-lib.so, phoenixbuilder-ios-executable, phoenixbuilder-macos, phoenixbuilder-macos-x86_64, phoenixbuilder-macos-arm64, phoenixbuilder-windows-executable-x86.exe, phoenixbuilder-windows-executable-x86_64.exe should not deploy to gui/ subdirectory

**Comment by LNSSPsd** [comment]
They are GUI binaries, but having the same name w/ CLI binaries.
