### ISSUE TITLE
Update Schematic block mapping

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#56]
[https://github.com/LNSSPsd/PhoenixBuilder/commit/cb1fd35ed60d9b52c6a85ab45c262812cc587e4f#diff-cb6e0405392536eddbdcc8e97f51b47cb640a51df91496c7829aa0814c0474e3](url)

the block mapping of schematic (not schem) file is too old, I managed to fix some, but many of them are still incorrect. (fence flower piston shulker_box and so on)

**Comment by Torrekie** [comment]
how was it going?
