### ISSUE TITLE
这个问题是咋回事？fastbuilder没挂VPN进入服务器，则显示错误为111，挂了VPN进入则显示错误为EOF

### ISSUE THREAD

**Issue by lrh288** [LNSSPsd/PhoenixBuilder#58]
![Screenshot_2022_0709_220824](https://user-images.githubusercontent.com/108987761/178109448-a1c36379-ae8c-4ccb-af9c-b01fbd5581e2.png)
![Screenshot_2022_0709_215516_com tencent mobileqq](https://user-images.githubusercontent.com/108987761/178109457-4ac0efe7-ef66-4f0e-b1c8-ce30fd4a57ff.png)
#57

**Comment by LNSSPsd** [comment]
Issues unrelated to PhoenixBuilder itself shouldn't be submitted here.
