### ISSUE TITLE
Version:global-bedrock/v1.19.10   Can not build.

### ISSUE THREAD

**Issue by HouKy2006** [LNSSPsd/PhoenixBuilder#64]
![IMG_9290](https://user-images.githubusercontent.com/109544236/179564373-a332a0cf-c4b2-478d-8b87-364577b0fdb7.png)

It is really hard to build.(1.19.10 oversea ver)
Hahaha~

**Comment by HouKy2006** [comment]
Please help me with this issue.

**Comment by Torrekie** [comment]
fixed in 1d99228e279aebdd5bb7ab11854c67c9203c19c9
