### ISSUE TITLE
FB无法连接该服务器

### ISSUE THREAD

**Issue by 666QFF** [LNSSPsd/PhoenixBuilder#66]
![_}@)8GXW_H4)KTUZAG5@T88](https://user-images.githubusercontent.com/99183410/180118965-5368a770-48b8-4f50-b247-885b66e3a5dd.jpg)
![T A7(YIB3)@5N9LO`)E6PN7](https://user-images.githubusercontent.com/99183410/180118994-e518fb30-7b60-466d-9f7b-848286d8ecf4.jpg)
FB无法连接该服务器，重启，换设备，换辅助用户，服务器没有蹦，关闭命令方块也无法连接上

**Comment by Happy2018new** [comment]
多半是服务器假死造成的
假死指的是服务器对外显示打开，但实际上服务器核心已经关闭了的情况
这种情况下应该通知服主重启服务器
（反正我就这样解决的）
