### ISSUE TITLE
Omega_system的存档导出功能存在问题

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#67]
Omega_system的新版本还未更新到FastBuilder中，但已经发现了如下问题：
在导出的世界中，若开启创造模式并飞行，则不能移动
经过测试，目前已知飞行时不能移动，如果是普通的行走状态则可以正常移动
版本：1.19.10 win10版

**Comment by Torrekie** [comment]
Is this problem still unresolved?

**Comment by CMA2401PT** [comment]
可能是版本不完全匹配导致的，你可以直接复制任意存档的 level.dat 到导出存档即可，omega 并不依赖level.dat的信息，只是简单的生成一个 level.dat 供基岩版读取
