### ISSUE TITLE
Version:global-bedrock/v1.19.10 Can not build.

### ISSUE THREAD

**Issue by HouKy2006** [LNSSPsd/PhoenixBuilder#68]
![1EE6761F-BB23-4BA4-86FC-65C0386FB95A](https://user-images.githubusercontent.com/109544236/180257238-70e05a96-6e2b-4473-8990-e90cdeb8d949.png)

**Comment by LNSSPsd** [comment]
Your system doesn't have libreadline-dev installed.

**Comment by HouKy2006** [comment]
thanks
