### ISSUE TITLE
`Bdump`模块无法在非主世界维度加载建筑

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#75]
无法在非主世界维度导入`.bdx`文件
我只测试了**仅**包含命令方块的`.bdx`文件，其他文件没有测试
具体可见此压缩包内的文件（此文件由`python`代码直接通过`.mcfunction`文件转换得到，因此没有签名）
[ans.zip](https://github.com/LNSSPsd/PhoenixBuilder/files/9228984/ans.zip)

**Comment by Happy2018new** [comment]
导入时已经将`bot`传送到了对应维度

**Comment by Happy2018new** [comment]
尽管`bot`在非主世界维度且设定的导出地点在非主世界维度，但`bot`依然会在主世界的对应位置加载建筑

**Comment by LNSSPsd** [comment]
This is a known issue as our SubChunkRequest packet only requests Overworld Dimension's chunk data in the specific position.

Support for other dimensions may be added later, before that, you can use `lexport` for unsuitable environment.

**Comment by Happy2018new** [comment]
This way is only talk about how to export builds from the server, but not to import……
