### ISSUE TITLE
证书过期（？）

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#76]
如下图所示
<img width="639" alt="image" src="https://user-images.githubusercontent.com/109064184/182058114-fb582c79-d9b0-4f04-b546-768c672bb05f.png">
<img width="518" alt="bf3a45fcae5bbcefe630513619c5b06b" src="https://user-images.githubusercontent.com/109064184/182058772-e777cf36-798e-4b82-b22b-249a5953b35e.png">

**Comment by LNSSPsd** [comment]
This repository is **not** for the authentication server, and things related with it shouldn't be reported here.
