### ISSUE TITLE
what about open a new branch for international version?

### ISSUE THREAD

**Issue by CMA2401PT** [LNSSPsd/PhoenixBuilder#8]
I know there already exist a FB lambda, that project is very nice, but some functions are missing. For example, if we can exchange bdx betwwen rental server and international (official) version, it could be great help. 
And I already have a very rough support for that.

**Comment by LNSSPsd** [comment]
Using a fake player to build structures in a Bedrock Dedicated Server could be inefficient since the server under your own control.
Making a mod or a tool that able to interact w/ the level storage may be a better way.

**Comment by CMA2401PT** [comment]
Ok, i'll try converting .bdx to some other format like mcstructure or level.db/mcfunction




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月27日(星期四) 晚上11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LNSSPsd/PhoenixBuilder] what about open a new branch for international version? (Issue #8)





 
Using a fake player to build structures in a Bedrock Dedicated Server could be inefficient since the server under your own control.
 Making a mod or a tool that able to interact w/ the level storage may be a better way.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
