### ISSUE TITLE
在 `BDX` 中支持一个可选的 `Operation`  ，用于记录方块或实体的 `NBT` 数据

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#83]
如标题所示，以珊瑚为例，在珊瑚处放置水方块并使用命令 `export` 将其导出，之后加载出的建筑结构不会包含水。
未测试 `lexport` 之情况。
已确认按顺序执行下述 `Minecraft Bedrock Edition` 原版命令可以解决问题：
```
setblock [posA] water [data]
setblock [posA] [blockId] [data]
```
可能受影响的方块：
```
minecraft:ladder
minecraft:coral
各类告示牌
```
若为旧版 `BDX` 格式，则使用此内容可解决问题(已确认含水珊瑚可解决)：
`BD@BDX\x00Demo\x00\x01coral\x00\x01water\x00\x07\x00\x01\x00\x00\x07\x00\x00\x00\x00XE`
样例文件(旧版格式)：
[ans.zip](https://github.com/LNSSPsd/PhoenixBuilder/files/9317593/ans.zip)
***
**其他（重要）**
如果采纳本 `issue` 所提及之解决方法，那么 `omega` 导入 `.bdx` 文件时不应该永远只放置最后声明的方块。

**Comment by Happy2018new** [comment]
需要注意的是，如果修复了本 `issue` 所提及之内容，那么在导入完后输出的 `已放置方块数` 应该不重复计算。

**Comment by CMA2401PT** [comment]
方块“被充水”是一种状态信息，事实上这也是通过nbt的方式描述的

值得注意的一点是，和其它文件形式不一样，bdx并非是一种对建筑结构的描述，而是一种对构建建筑过程的描述

基于上述观点，首先你的提议确实是可行的，即：将一个充水的方块表述为由两步完成的构造，但是同样也可以描述为：构造一个充水的方块。

这两者之间的差距是巨大的，或者说是两种完全不同的处理思路。比如说，我们现在并不能放下一个带字的告示牌，但是或许某一天我们可以做的这个，那么此时如果按你的思路，从能做到的那天起，产生的bdx文件才包含对于构造一个带字的告示牌的过程描述

而我个人倾向的观点是，即使现在并不能构造某种nbt方块，我们也应该在bdx里添加某种 “通用”的方块nbt描述，这样，在某一天我们有能力支持某种nbt的生成时，就可以自然的支持以前生成的bdx

**Comment by Happy2018new** [comment]
我想我们等不到那天的到来了，官方永远不会支持向方块亦或实体写入 `NBT` 数据。
因此，建议添加一个 `Operation 39` ，用于保存二进制形式的 `NBT` 数据。
为了通用性，建议以 `Minecraft Java Edition` 中命令的 `NBT` 为参考。

**Comment by LNSSPsd** [comment]
Format will be:
```
unsigned char command=39;
unsigned int length;
...(buffer)
```
WIP

**Comment by Happy2018new** [comment]
> Format will be:
> 
> ```
> unsigned char command=39;
> uint32_t length;
> ...(buffer)
> ```
> 
> WIP

希望此特性得到更新后，相应的 `bdump` 及 `bdump-cn` 解析文档也会得到更新。
😊

**Comment by Happy2018new** [comment]
The Chinese version may be:
```
unsigned char command=39;
uint32_t 二进制形式下NBT的长度
...(对应的NBT字符串在经过 `encode` 后的二进制形式)
```

**Comment by LNSSPsd** [comment]
Reserved command 39.
It is only a buffer command, telling reader to go through itself, but will not be the final form of NBT related command.
