### ISSUE TITLE
`resume` argument works incorrectly for command `bdump`

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#84]
摘要：
当暂停了由 `bdump` 创建的任务后，之后恢复此任务会在错误的位置继续生成方块(有一定的偏移)
***
影响版本（以当前版本计算起）：
```
3.1.0 (fea7bda)
```
***
复现步骤：
1. 下载这个文件(旧版 `BDX` )
[ans.zip](https://github.com/LNSSPsd/PhoenixBuilder/files/9331258/ans.zip)
2. 下载此版本，即 `3.1.0 (fea7bda)` 版本的 `FastBuilder` 
[FastBuilder.zip](https://github.com/LNSSPsd/PhoenixBuilder/files/9331262/FastBuilder.zip)
3. 解压以上两个压缩包并置于同一文件夹下
4. 运行解压出来的 `FastBuilder.exe`
5. 进入任意一个租赁服且确保 `辅助用户` 在此租赁服有 `管理员权限`
6. 按从上到下的顺序依次执行以下命令
```
delay set 2400
set 0 -60 0
bdump -p ans.bdx -resume 12
task pause 1
```
7. 然后等待几秒钟，之后执行命令 `task resume 1`
***
观察结果：
`辅助用户` 在另外一个地方构建建筑物
***
预期结果：
`辅助用户` 在暂停的位置恢复构建
***
演示视频（需下载压缩包并解压）：
https://wwc.lanzouv.com/iqHfG09i018h
***
`Bug` 影响评估：
严重(可能)

**Comment by CMA2401PT** [comment]
这是一个很容易修复的小问题，我注意到你有一定编程能力，既然你有时间去仔细的描述这个问题，何不自学一下golang然后拿这个问题试试手呢？

**Comment by Happy2018new** [comment]
> 这是一个很容易修复的小问题，我注意到你有一定编程能力，既然你有时间去仔细的描述这个问题，何不自学一下golang然后拿这个问题试试手呢？

这是一个极好的建议，我会抽空学习其他语言的。

**Comment by LNSSPsd** [comment]
3b94aaf
