### ISSUE TITLE
严重的安全性问题(关于 `export` 和 `lexport` )

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#86]
已确认 `辅助用户` 仍然可以在没有 `管理员权限` 的情况下利用 `lexport` 和 `export` 导出建筑物，只要确保 `辅助用户` 在导出区域且位于地表上。
其他说明：`spreaplayers` 会按照 `正态分布` 将实体散布到地表上。

**Comment by Happy2018new** [comment]
`omega` 插件由于内置了 `管理员权限检测` 插件且强制启用，因此不受影响

**Comment by LNSSPsd** [comment]
This is not a security problem, using features without **CLIENT's** limit is user's freedom.

**Comment by Happy2018new** [comment]
![image](https://user-images.githubusercontent.com/109064184/184520429-32ec1b67-850e-4917-9191-8c1435663818.png)
我看不懂，但我大受震撼。
I can't understand, I was very surprised.
