### ISSUE TITLE
有关 `BDump` 的相关请求(`Request`)

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#90]
在修复了 [#75](https://github.com/LNSSPsd/PhoenixBuilder/issues/75) 所述的问题之后，效率得到了大幅度的降低。原本 `1000Blocks/s` 的速度必须要降到 `20Blocks/s` 左右才能正常使用，这是**沉重的代价**。

所以，希望可以让机器人自己检测所在维度。如果是主世界，则使用旧方法导入，否则使用新方法(但效率极其慢的方法)。

**Comment by Happy2018new** [comment]
Torrekie 认为可能存在更好的解决办法。
因此，本 `Issue` 所述之方案是最后的解决办法。
相关聊天如图所示。
![image](https://user-images.githubusercontent.com/109064184/186902181-151711ad-ca7e-4474-81f6-1e8116fe14d5.png)

**Comment by LNSSPsd** [comment]
Solved by cancelling the support for building over non-overworld dimensions.
