### ISSUE TITLE
torrekie骚话

### ISSUE THREAD

**Issue by XiaoLu521QwQ** [LNSSPsd/PhoenixBuilder#95]
在启动fastbuilder时 随机取一句 
torrekie骚话 并打印在控制台
该骚话集随fb迭代进行迭代

**Comment by LNSSPsd** [comment]
Note: keep sending spam will get you banned from this project.

**Comment by poppweixing** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈
