### ISSUE TITLE
`export` 问题

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#96]
反正，下图的问题还是存在，具体如何复现我也不清楚。
![4c5953a34633ded20b79d51f04975614](https://user-images.githubusercontent.com/109064184/189692156-dc15d045-ac2b-448f-bd41-93f99380b889.jpg)

**Comment by Happy2018new** [comment]
图是别人的（

**Comment by Torrekie** [comment]
can you reproduce this

**Comment by Happy2018new** [comment]
I've triggered this before.
But I found that I can not reproduce this bug.
Maybe I need provide the number of my server. Of course, I also will provide the password. I'll do that if I have to.
@Torrekie

**Comment by LNSSPsd** [comment]
Full backtrace log is required.
The provided photo only gave the last few lines of it, which is hard to locate the error.

**Comment by LNSSPsd** [comment]
Note: Providing privacy-related information is not recommended.

**Comment by Happy2018new** [comment]
Ok, I'll try another way to describe this issue.

**Comment by Happy2018new** [comment]
> Note: Providing privacy-related information is not recommended.

Ok, I'll try another way to describe this issue.

**Comment by Happy2018new** [comment]
> Full backtrace log is required. The provided photo only gave the last few lines of it, which is hard to locate the error.

Ok, I see. I will provide detailed logs later if I can still trigger the bug.

**Comment by Happy2018new** [comment]
此问题暂时作为 `Not Planned` 关闭。
待我何时可以精确的复现此问题，再重新打开。
