### ISSUE TITLE
关于OmegaSide的一个错误

### ISSUE THREAD

**Issue by Liliya233** [LNSSPsd/PhoenixBuilder#97]
**在多人游戏环境下，使用OmegaSide可能会引发`concurrent write to websocket connection`的错误**

![1](https://user-images.githubusercontent.com/79683806/191808736-a1e7b935-0b90-4694-839e-a1a1a817137d.png)

**已确定可以通过以下的步骤来复现该问题：**
1. 将以下内容的插件放入`omega_storage\side\omega_python_plugins`目录下
~~~
# 插件: 开
from omega_side.python3_omega_sync import API
from omega_side.python3_omega_sync import frame as omega
from omega_side.python3_omega_sync.bootstrap import install_lib
from omega_side.python3_omega_sync.protocol import *
 
def plugin(api:API):
    def on_menu_invoked(player_input:PlayerInput):
        api.do_send_ws_cmd("testfor @r",cb=None)
    api.listen_omega_menu(triggers=["test"], argument_hint="", usage="test", on_menu_invoked=on_menu_invoked, cb=None)

omega.add_plugin(plugin=plugin)
omega.run(addr=None)
~~~
2. 使用`Omega启动器`进入租赁服
3. 使用循环命令方块重复且较快地调用`test菜单项`(模拟多名玩家频繁使用菜单)

![2](https://user-images.githubusercontent.com/79683806/191810330-69035e9f-6233-40f8-8d7f-0757a2b14489.png)

4. 稍等片刻后即可复现此错误，同时对`test菜单项`的调用不再有回应

**Comment by CMA2401PT** [comment]
啊，原来go的ws不是并发安全的吗？好吧，晚点我给它上一个互斥锁

**Comment by CMA2401PT** [comment]
done

**Comment by Torrekie** [comment]
> done

remember adding issue number to corresponding commit's message to close it as completed.
