### ISSUE TITLE
关于Omega玩家商店组件的错误

### ISSUE THREAD

**Issue by Liliya233** [LNSSPsd/PhoenixBuilder#98]
### 错误描述
**购买离线玩家的商品后，重新启动Omega会出现以下错误**
```
18:18:29  SUCCESS  正在加载组件  43/ 83 [Built-In] 玩家商店@0.0.1
 ERROR  正在加载的组件配置文件不正确，因此 Omega 系统拒绝启动，具体错误如下:
        json: cannot unmarshal object into Go struct field Cmd.下次上线时执行的指令.指令.LuaValue of type omega_lua.Value
        建议根据说明修改对应的配置文件，如果你修不好了，删除对应配置文件即可
18:18:29 正在保存数据并关闭系统...
```
**部分配置如下**
```
...
"成功售出时的加钱指令": [
  "tellraw [出售者] {\"rawtext\":[{\"text\":\"§e[玩家商店] §a你上架的商品(§e[商品]§a)已被§e[购买者]§a购买！\"}]}",
  "tellraw [出售者] {\"rawtext\":[{\"text\":\"§e[玩家商店] §a商品售出收益(§9[实际收益]§a)§7(已扣除手续费§9[所得税]§7)\"}]}",
  "scoreboard players add [出售者] [货币计分板名] [实际收益]"
],
...
```
### 临时解决方法
**1. 根据错误信息，在玩家商店的数据文件内找到以下内容**
```
{
  "下次上线时执行的指令": {
    "00000000-0000-4000-8000-...": [
      {
        "玩家": "somebody",
        "指令": [
          {
            "指令": "tellraw [出售者] {\"rawtext\":[{\"text\":\"§e[玩家商店] §a你上架的商品(§e[商品]§a)已被§e[购买者]§a购买！\"}]}",
            "执行前延迟": 0,
            "执行后延迟": 0,
            "结果记录": "",
            "身份": "WS",
            "备注": "",
            "LuaValue": {}
          },
...
```
**2. 尝试将`"LuaValue": {}`修改为`"LuaValue": null`**，修改后的内容如下：
```
{
  "下次上线时执行的指令": {
    "00000000-0000-4000-8000-...": [
      {
        "玩家": "somebody",
        "指令": [
          {
            "指令": "tellraw [出售者] {\"rawtext\":[{\"text\":\"§e[玩家商店] §a你上架的商品(§e[商品]§a)已被§e[购买者]§a购买！\"}]}",
            "执行前延迟": 0,
            "执行后延迟": 0,
            "结果记录": "",
            "身份": "WS",
            "备注": "",
            "LuaValue": null
          },
...
```
**3. 重新启动Omega，无报错且玩家商店能够正常使用**

### 总结
**因为使用以上的方法能够使玩家商店恢复正常，所以很可能不是配置文件的问题..**

**Comment by CMA2401PT** [comment]
已修复

**Comment by CMA2401PT** [comment]
本质上来说，这个问题是因为 omega 配置中指令序列发生了根本性的变换，但是内部实现的隐藏没有做好导致的，以这条指令为例：
give [player] [decide_reward<[score<[player],coin>]>]
在较早的时候，omega仅对诸如 [player] 等做简单替换，并硬编码了 [score<scorebaord>] 或 [score<player,scoreboard>] 的实现，但是自引入 Lua 之后，此行命令将被解析为 AST，并具有独立于lua的栈空间:

give #VAL1 #VAL2 
#VAL1 (类型: CouldBeVar) = 变量 player 的值或常量字符串 "[player]"
#VAL2 (类型: CouldBeFuncReturn) = lua 函数 decide_reward(#VAL3) 或字符串序列 "[decide_reward<"+#VAL3+">]" 的值
#VAL3 (类型: CouldBeFuncReturn) =  lua 函数 score(#VAL4,coin) 或字符串序列  "[score<"+#VAL4+",coin>]"  的值
#VAL4 (类型: CouldBeVar) = 变量 player 的值或常量字符串 "[player]"

对于类型 CouldBeVar 的表达式来说，其值究竟是变量还是字符串取决于组件是否传入该变量
对于类型 CouldBeFuncReturn 的表达式来说，其值究竟是 lua 函数的返沪指还是字符串序列的值取决于该组件配置文件中携带的lua代码段中是否调用 omega.register_func 函数暴露对应 lua 的调用

**Comment by Happy2018new** [comment]
建设性信息/温馨提示
***
此议题所述之问题或漏洞仍旧存在吗？
若本议题已被解决，请关闭其，否则请维持其。
