### ISSUE TITLE
有关 `Omega` 的 `存档功能` 的相关错误

### ISSUE THREAD

**Issue by Happy2018new** [LNSSPsd/PhoenixBuilder#99]
近日，发现 `Omega` 的 `镜像存档` 功能不能再导出含有指令的 `命令方块` 和含有物品数据的 `容器` 。
同样的，使用其 `导出存档` 功能时，相关的观察结果与 `镜像存档` 的结果一致。
在使用 `lexport` 命令导出命令方块时，发现命令方块数据不会丢失，因此我认为这可能只是 `Omega` 自己的问题。

**Comment by LNSSPsd** [comment]
Closed as duplicated with #100 while that one has more comments.
